using System;using System.Drawing;using System.IO;using System.Linq;using System.Windows.Forms;
namespace GameCoach {
partial class Coach {
 WorkspaceNav workspace;Button silence,sendQuestion;CurrentBuildPanel buildCards;string visualSession;
 void BuildWorkspace(out TableLayoutPanel root,out Action wrap){
  AutoScaleMode=AutoScaleMode.None;Font=new Font("Segoe UI",10);BackColor=Theme.Bg;ForeColor=Theme.Text;
  using(var g=CreateGraphics())Theme.Scale=Math.Max(1,g.DpiX/96f);
  Icon=AppGlyph.WindowIcon();Text="Game Coach · The Crossroads";StartPosition=FormStartPosition.CenterScreen;
  var area=Screen.PrimaryScreen.WorkingArea;ClientSize=new Size(Math.Min(Theme.P(1150),area.Width-60),Math.Min(Theme.P(860),area.Height-80));MinimumSize=new Size(Math.Min(Theme.P(850),area.Width-40),Math.Min(Theme.P(630),area.Height-60));
  var shell=Theme.Stack();shell.SuspendLayout();shell.Dock=DockStyle.Fill;shell.AutoSize=false;shell.Padding=new Padding(Theme.P(20));Controls.Add(shell);root=shell;
  var header=Theme.Stack(3);header.ColumnStyles.Clear();header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,Theme.P(60)));header.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,Theme.P(205)));
  header.Controls.Add(new PictureBox{Image=AppGlyph.Brand(Theme.P(48)),SizeMode=PictureBoxSizeMode.Zoom,Size=new Size(Theme.P(48),Theme.P(48)),Margin=new Padding(0,0,Theme.P(12),0)},0,0);
  var brand=Theme.Stack();Theme.Row(brand,Theme.Heading("Game Coach",22));Theme.Row(brand,Theme.Copy("THE CROSSROADS   /   HADES II"));header.Controls.Add(brand,1,0);
  listen=Theme.Action("Start coaching","play","Starts voice listening and the local watcher, then minimizes this window. Your saved run stays intact.",(s,e)=>{if(listening||busy)Stop();else{Start(false);if(listening)WindowState=FormWindowState.Minimized;}});listen.AutoSize=false;listen.Dock=DockStyle.Fill;listen.Font=new Font("Segoe UI Semibold",12);listen.BackColor=Theme.Mint;listen.ForeColor=Theme.Bg;header.Controls.Add(listen,2,0);Theme.Row(shell,header);
  status=Theme.Copy("Ready when you are. Start coaching to listen and watch together.");status.ForeColor=Theme.Mint;Theme.Row(shell,status);
  workspace=new WorkspaceNav(Theme.Scale);int row=shell.RowCount++;shell.RowStyles.Add(new RowStyle(SizeType.Percent,100));shell.Controls.Add(workspace,0,row);
  var coachPage=Theme.Page();workspace.Add("Coach",coachPage);var content=Theme.Stack();content.Dock=DockStyle.Fill;content.AutoSize=false;coachPage.Controls.Add(content);Theme.ScrollLayout(coachPage,content,505);
  Theme.Row(content,Theme.Heading("A second perspective",24));Theme.Row(content,Theme.Copy("Cards handle the choices. Talk to your coach about the plan."));
  var voice=Theme.Section("Talk while you play","Say “coach”, wait for the tone, then ask your question.");
  var voiceActions=Theme.Flow();activate=Theme.Action("Ask by voice","mic","Record a question now. During a reply, this interrupts it and opens the microphone for your new question.",(s,e)=>{if(replySpeech!=null||busy)InterruptSpeech(true);else{if(!listening)Start(false,false);if(listening)ActivateQuestion();}});voiceActions.Controls.Add(activate);
  silence=Theme.Action("Silence reply","mute","Same as saying “thanks”. Stops the current speech; listening, your run and the watcher continue.",(s,e)=>InterruptSpeech(false));silence.Enabled=false;voiceActions.Controls.Add(silence);Theme.Row(voice,voiceActions);
  meter=new ProgressBar{Height=Theme.P(4),Maximum=100,Style=ProgressBarStyle.Continuous};Theme.Hint(meter,"Microphone input level. Quiet means no sound is arriving; it does not mean the run has ended.");Theme.Row(voice,meter);micStatus=Theme.Copy("Microphone off");Theme.Row(voice,micStatus);Theme.Row(content,voice);
  var qrow=Theme.Stack(2);qrow.ColumnStyles.Clear();qrow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));qrow.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
  question=new TextBox{Dock=DockStyle.Fill,AccessibleName="Question",Margin=new Padding(0,Theme.P(9),Theme.P(10),Theme.P(9))};Theme.Hint(question,"Type a question about your build or a choice, then press Enter. The coach uses your saved build and a fresh screen capture.");qrow.Controls.Add(question,0,0);
  sendQuestion=Theme.Action("Send","send","Ask the cloud coach with your typed question and current game context. Uses API credits.",async(s,e)=>{if(!busy)await Submit(question.Text);});qrow.Controls.Add(sendQuestion,1,0);question.KeyDown+=async(s,e)=>{if(e.KeyCode==Keys.Enter){e.SuppressKeyPress=true;if(!busy)await Submit(question.Text);}};
  Theme.Row(content,Theme.Heading("Or type a question",13));Theme.Row(content,qrow);
  answer=Theme.ReadBox();answer.AccessibleName="Coach answer";answer.Text="Ask about the decision behind the decision.\r\n\r\n• Which part of this build should I improve next?\r\n• How does this boon interact with my current setup?\r\n• Explain the boss tips.\r\n\r\nYour latest reply will appear here.";answer.LinkClicked+=(s,e)=>OpenSource(e.LinkText);row=content.RowCount++;content.RowStyles.Add(new RowStyle(SizeType.Percent,100));content.Controls.Add(answer,0,row);
  heardStatus=Theme.Copy("Your recognized question will appear here.");Theme.Row(content,heardStatus);watcherStatus=Theme.Copy("Watcher off · starts with coaching");Theme.Row(content,watcherStatus);
  privacy=Theme.Copy("Local watching • Cloud conversations and speech");Theme.Hint(privacy,"Wake detection, screenshots used by the watcher and game-save reading stay on this PC. An activated voice question uses cloud transcription, coaching and speech.");Theme.Row(content,privacy);
  var memoryPage=Theme.Page();var memory=Theme.Stack();memory.Dock=DockStyle.Top;memoryPage.Controls.Add(memory);Theme.Row(memory,Theme.Heading("Current build",24));buildSummary=Theme.Copy("");Theme.Row(memory,buildSummary);
  var memoryActions=Theme.Flow();memoryActions.Controls.Add(Theme.Action("Refresh checkpoint","refresh","Read the latest local game save. Unrecorded changes cannot be recovered until Hades saves.",(s,e)=>{SaveMemorySync.Refresh(true);RefreshMemory();}));
  setupButton=Theme.Action("Capture starting setup","layers","Optional: begin fresh coaching notes and capture the visible equipment screens every 4 seconds for up to 60 seconds. Cloud analysis runs when you finish.",(s,e)=>{if(setupReview)FinishSetup();else BeginSetup();});memoryActions.Controls.Add(setupButton);Theme.Row(memory,memoryActions);
  buildCards=new CurrentBuildPanel();buildCards.Height=Theme.P(340);Theme.Row(memory,buildCards);
  memoryView=Theme.ReadBox();memoryView.Height=Theme.P(250);memoryView.AccessibleName="Memory diagnostics";memoryView.LinkClicked+=(s,e)=>OpenSource(e.LinkText);Theme.Row(memory,Theme.Fold("Evidence & coaching notes","Inspect the detailed saved choices, player reports and coaching notes. This is a diagnostic view.",memoryView));workspace.Add("Current build",memoryPage);
  sandbox=new SandboxPanel(RunExperiment,text=>{if(!busy){workspace.Select(0);question.Text=text;var task=Submit(text);}});workspace.Add("Sandbox",sandbox);workspace.Add("Activity",new UsagePanel());runArchive=new RunArchivePanel();workspace.Add("Run history",runArchive);
  var settingsPage=Theme.Page();workspace.Add("Settings",settingsPage);var settingsLayout=Theme.Stack();settingsPage.Controls.Add(settingsLayout);
  Theme.Row(settingsLayout,Theme.Heading("Settings",24));Theme.Row(settingsLayout,Theme.Copy("Balance the voice, choose a display, and manage your connections."));
  var voiceBody=Theme.Stack();settingsPanel=voiceBody;Theme.Row(settingsLayout,voiceBody);
  var audioCard=Theme.Section("Voice & playback","Volume and speed can change while you play.");Theme.Row(voiceBody,audioCard);
  voices=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,AccessibleName="Cloud voice"};voices.Items.AddRange(new object[]{"marin","cedar","alloy","ash","ballad","coral","echo","sage","shimmer","verse"});voices.SelectedItem=voices.Items.Contains(settings.Voice)?settings.Voice:"marin";Theme.Row(audioCard,Theme.Copy("Voice"));Theme.Row(audioCard,voices);Theme.Hint(voices,"The OpenAI speech voice used for replies and optional run greetings. Changing voices can require a fresh voice request.");
  voiceVolume=new TrackBar{Minimum=0,Maximum=100,TickFrequency=25,Value=Math.Max(0,Math.Min(100,settings.VoiceVolume)),AccessibleName="Voice volume",Height=Theme.P(36)};voiceControlsLabel=Theme.Copy(voiceVolume.Value+"%");Theme.Row(audioCard,Theme.Copy("Volume"));Theme.Row(audioCard,SliderRow(voiceVolume,voiceControlsLabel));voiceVolume.ValueChanged+=(s,e)=>{voiceControlsLabel.Text=voiceVolume.Value+"%";settings.VoiceVolume=voiceVolume.Value;Store.Save(settings);};Theme.Hint(voiceVolume,"Set to 0 for silent answers. Voice listening and on-screen advice remain available.");
  voiceRate=new TrackBar{Minimum=-3,Maximum=3,TickFrequency=1,Value=Math.Max(-3,Math.Min(3,settings.VoiceRate)),AccessibleName="Speech speed",Height=Theme.P(36)};var rate=Theme.Copy(voiceRate.Value==0?"Normal":voiceRate.Value.ToString("+0;-0"));Theme.Row(audioCard,Theme.Copy("Speech speed"));Theme.Row(audioCard,SliderRow(voiceRate,rate));voiceRate.ValueChanged+=(s,e)=>{rate.Text=voiceRate.Value==0?"Normal":voiceRate.Value.ToString("+0;-0");settings.VoiceRate=voiceRate.Value;Store.Save(settings);};
  runGreetings=new CheckBox{Text="Encourage me at the start and celebrate my wins",AutoSize=true,Checked=settings.RunGreetings,AccessibleName="Run greetings"};Theme.Row(audioCard,runGreetings);Theme.Hint(runGreetings,"A short locally written message for new runs and victories, spoken with your cloud voice. Speech uses API credits.");runGreetings.CheckedChanged+=(s,e)=>{settings.RunGreetings=runGreetings.Checked;Store.Save(settings);if(!settings.RunGreetings){CancelMoment();if(moments!=null)moments.Clear();}};
  Theme.Row(audioCard,Theme.Action("Preview voice","play","Play a short sample using your selected cloud voice. Pause coaching first; the sample uses speech credits.",async(s,e)=>{if(busy||listening){SetStatus("Pause coaching before previewing a voice.");return;}busy=true;try{SaveSettings();await Speak("I'm your game coach. Let's make this a good run.");}catch(Exception ex){SetStatus(ex.Message);}finally{busy=false;}}));
  var input=Theme.Section("Listening & capture");Theme.Row(voiceBody,input);var inputFields=Fields();Theme.Row(input,inputFields);wake=OptionField(inputFields,"Wake phrase",settings.Wake);Theme.Hint(wake,"Local wake recognition listens for this phrase. “coach” also works. Wait for the tone before the question.");mic=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList};mic.Items.Add("Windows default microphone");mic.SelectedIndex=0;OptionRow(inputFields,"Microphone",mic);Theme.Hint(mic,"Uses the Windows default recording device through WASAPI. Change the device in Windows Sound settings.");
  display=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,AccessibleName="Capture display"};int selected=0;for(int i=0;i<Screen.AllScreens.Length;i++){var screen=Screen.AllScreens[i];display.Items.Add("Display "+(i+1)+" · "+screen.Bounds.Width+" × "+screen.Bounds.Height);if(screen.DeviceName==settings.Display||(settings.Display==""&&screen.Primary))selected=i;}display.SelectedIndex=selected;OptionRow(inputFields,"Game display",display);Theme.Hint(display,"Display used for on-demand questions and setup captures. Keep the game visible there. The automatic watcher checks the foreground Hades window separately.");
  var account=Theme.Section("Cloud coach","Add an OpenAI Platform API key here. Your ChatGPT subscription is separate from API billing.");Theme.Row(voiceBody,account);var keyRow=Fields();key=new TextBox{UseSystemPasswordChar=true,AccessibleName="API key"};OptionRow(keyRow,"API key",key);Theme.Hint(key,"Leave blank to keep the saved key. Keys are stored with Windows user encryption and excluded from run exports.");Theme.Row(account,keyRow);Theme.Row(account,Theme.Action("Save API key","check","Encrypt and save the key entered above. The masked field is cleared afterward.",(s,e)=>{try{if(string.IsNullOrWhiteSpace(key.Text))throw new Exception("Enter a key in the masked field first.");Store.Key(key.Text.Trim());key.Clear();SetStatus("API key saved with Windows encryption.");}catch(Exception ex){SetStatus(ex.Message);}}));
  var advanced=Fields();model=OptionField(advanced,"Cloud coach model",settings.Model);game=OptionField(advanced,"Game context",settings.Game);Theme.Hint(model,"Model ID used for cloud reasoning and screenshot questions. This does not change the local model.");Theme.Hint(game,"Context sent to the voice coach. Automatic screen and save integration currently supports Hades II.");Theme.Row(account,Theme.Fold("Advanced coach options","Model and context settings. Pause coaching to change them.",advanced));
  Theme.Row(voiceBody,Theme.Action("Save preferences","check","Save voice, microphone, display and model preferences. Volume and speed already save automatically.",(s,e)=>{try{SaveSettings();SetStatus("Preferences saved.");}catch(Exception ex){SetStatus(ex.Message);}}));
  localPanel=new LocalPanel(RefreshMemory);localPanel.VictoryObserved+=r=>{if(moments!=null&&listening&&settings.RunGreetings){moments.Victory(r);MomentTick();}};localPanel.StatusChanged+=message=>{if(!closing)watcherStatus.Text="WATCHER · "+message;};localPanel.Dock=DockStyle.Top;localPanel.AutoSize=true;Theme.Row(settingsLayout,localPanel);
  workspace.Add("How to use",GuidePages.HowTo());workspace.Add("About",GuidePages.About(settings));
  usage=Theme.Copy("Local watching. On-demand cloud coaching.");usage.Font=new Font("Segoe UI",8);Theme.Row(shell,usage);
  Theme.StyleInputs(this);RefreshMemory();shell.ResumeLayout(true);wrap=()=>{Theme.Reflow(shell);};
 }
 static TableLayoutPanel Fields(){var table=Grid(2);table.Dock=DockStyle.Top;table.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,Theme.P(155)));table.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));return table;}
 void UpdateActions(){if(silence==null)return;silence.Enabled=replySpeech!=null;activate.Text=replySpeech!=null||busy?"Interrupt & ask":"Ask by voice";activate.Enabled=mode!="Recording"&&mode!="Transcribing";sendQuestion.Enabled=!busy&&!string.IsNullOrWhiteSpace(question.Text);string next=listening||busy?"pause":"play";if(next!=visualSession){visualSession=next;var old=listen.Image;listen.Image=AppGlyph.Draw(next,Theme.P(18),listening||busy?Theme.Text:Theme.Bg);if(old!=null)old.Dispose();listen.ForeColor=listening||busy?Theme.Text:Theme.Bg;Theme.Hint(listen,listening||busy?"Pause voice listening and automatic watching. Your game and saved run continue unchanged.":"Start voice listening and the local watcher, then minimize this window. Keeps your current run memory.");}}
}
}
