using System;using System.IO;using System.Linq;using System.Drawing;using System.Collections.Generic;using System.Windows.Forms;
namespace GameCoach {
static class BoonArt {
 static Dictionary<string,string> index;static readonly Dictionary<string,Bitmap> images=new Dictionary<string,Bitmap>();
 internal static string Root {get{string p=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets");return p;}}
 internal static string PathFor(string id){try{if(index==null)index=Store.Json.Deserialize<Dictionary<string,string>>(File.ReadAllText(Path.Combine(Root,"boon-icons.json")));string name;if(id==null||!index.TryGetValue(id,out name))return "";string path=Path.GetFullPath(Path.Combine(Root,name));return path.StartsWith(Path.GetFullPath(Root)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase)&&File.Exists(path)?path:"";}catch{return "";}}
 internal static Bitmap Get(string id){Bitmap result;if(images.TryGetValue(id??"",out result))return result;string path=PathFor(id);if(path.Length==0)return null;using(var image=Image.FromFile(path))result=new Bitmap(image);images[id]=result;return result;}
 internal static string Data(string id){string path=PathFor(id);return path.Length==0?"":"data:image/png;base64,"+Convert.ToBase64String(File.ReadAllBytes(path));}
 internal static Color Rarity(string value){switch((value??"").ToLowerInvariant()){case "rare":return Color.FromArgb(113,184,237);case "epic":return Color.FromArgb(185,147,238);case "heroic":return Color.FromArgb(238,143,163);case "duo":return Color.FromArgb(211,221,115);case "legendary":return Color.FromArgb(243,187,97);default:return Theme.Muted;}}
 internal static string Meta(RecapItem i){return RecapDetails.Rarity(i)+" · "+i.category+(i.level<=0&&i.rank<=0&&i.category!="Arcana"&&i.category!="Aspect"&&i.category!="Keepsake"?" · level not recorded":"");}
 internal static string Detail(RecapItem i){return i.name+"\r\n"+Meta(i)+"\r\n\r\n"+(string.IsNullOrEmpty(RecapDetails.Effect(i))?"Exact effect not retained for this run.":RecapDetails.Effect(i))+"\r\n\r\n"+(i.evidence??"Game history; exact level may be unavailable.");}
 internal static Control Tile(RecapItem i){var card=new Button{Width=Theme.P(220),Height=Theme.P(86),Text=i.name+"\r\n"+RecapDetails.Rarity(i),TextAlign=ContentAlignment.MiddleLeft,Font=new Font("Segoe UI",9),FlatStyle=FlatStyle.Flat,BackColor=Theme.Card,ForeColor=Theme.Text,Margin=new Padding(0,0,Theme.P(8),Theme.P(8)),Padding=new Padding(Theme.P(8)),Cursor=Cursors.Hand,AccessibleName=i.name+", "+RecapDetails.Rarity(i),TextImageRelation=TextImageRelation.ImageBeforeText};card.FlatAppearance.BorderColor=Rarity(i.rarity);var art=Get(i.id);if(art!=null){var ownedImage=new Bitmap(art,new Size(Theme.P(58),Theme.P(58)));card.Image=ownedImage;card.ImageAlign=ContentAlignment.MiddleLeft;card.Disposed+=(s,e)=>ownedImage.Dispose();}Theme.Hint(card,Detail(i));card.Click+=(s,e)=>{using(var f=new Form{Text=i.name,Icon=AppGlyph.WindowIcon(),Size=new Size(Theme.P(540),Theme.P(400)),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Bg,ForeColor=Theme.Text,Font=new Font("Segoe UI",11),MinimizeBox=false,MaximizeBox=false}){var body=Theme.Page();f.Controls.Add(body);var stack=Theme.Stack();body.Controls.Add(stack);if(art!=null)Theme.Row(stack,new PictureBox{Image=art,Height=Theme.P(96),SizeMode=PictureBoxSizeMode.Zoom});Theme.Row(stack,Theme.Heading(i.name,20));Theme.Row(stack,Theme.Copy(Meta(i)));Theme.Row(stack,Theme.Copy(string.IsNullOrEmpty(RecapDetails.Effect(i))?"Exact effect not retained for this run.":RecapDetails.Effect(i)));Theme.Row(stack,Theme.Copy(i.evidence??"Game-save history"));f.ShowDialog(card.FindForm());}};return card;}
 internal static Control Grid(IEnumerable<RecapItem> items){var grid=Theme.Flow();foreach(var i in items)grid.Controls.Add(Tile(i));return grid;}
}
class CurrentBuildPanel:UserControl {
 readonly Panel scroll;readonly TableLayoutPanel content;readonly FlowLayoutPanel tabs;string selected="Boons",stamp="";
 internal CurrentBuildPanel(){Dock=DockStyle.Fill;BackColor=Theme.Bg;var root=Theme.Stack();root.Dock=DockStyle.Fill;root.AutoSize=false;Controls.Add(root);tabs=Theme.Flow();foreach(string name in new[]{"Boons","Arcana","Equipment"}){string page=name;tabs.Controls.Add(Theme.Button(name,(s,e)=>{selected=page;RefreshBuild(true);}));}Theme.Row(root,tabs);scroll=new Panel{Dock=DockStyle.Fill,AutoScroll=true};int row=root.RowCount++;root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.Controls.Add(scroll,0,row);content=Theme.Stack();scroll.Controls.Add(content);}
 internal void RefreshBuild(bool force=false){var b=RunMemory.Load().gameState;string next=b==null?"none":b.sourceRun+":"+b.fingerprint;if(!force&&stamp==next)return;stamp=next;content.SuspendLayout();while(content.Controls.Count>0){var c=content.Controls[0];content.Controls.Remove(c);c.Dispose();}content.RowCount=0;content.RowStyles.Clear();foreach(Button tab in tabs.Controls){tab.ForeColor=tab.Text==selected?Theme.Mint:Theme.Muted;Theme.Hint(tab,"Show your current saved "+tab.Text.ToLowerInvariant()+". Hover an item for its recorded effect.");}if(b==null)Theme.Row(content,Theme.Copy("Open Hades II and refresh the checkpoint to load your build."));else{
 var items=b.owned.Where(t=>t.name!=t.id&&!t.id.StartsWith("Dummy")).Select(t=>new RecapItem{id=t.id,name=t.name,category=t.category=="arcana"?"Arcana":t.category=="aspect"?"Aspect":t.category=="keepsake"?"Keepsake":HistoryProjection.Category(t.id,BuildPlanner.Names),rarity=t.rarity,level=t.level,rank=t.rank,description=t.description,effects=t.effectDetails,evidence="Current game checkpoint · "+DateTime.Parse(b.savedAt).ToLocalTime().ToString("HH:mm:ss")}).Where(i=>selected=="Arcana"?i.category=="Arcana":selected=="Equipment"?i.category=="Aspect"||i.category=="Keepsake":i.category!="Arcana"&&i.category!="Aspect"&&i.category!="Keepsake").ToArray();
 Theme.Row(content,Theme.Copy("Hover for effects and levels. Select an item to keep its details open."));Theme.Row(content,BoonArt.Grid(items));if(items.Length==0)Theme.Row(content,Theme.Copy("No items in this category were retained by the checkpoint."));}content.ResumeLayout(true);Theme.Reflow(content);}
}
}
