using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Windows.Forms;
namespace GameCoach {
public class UnlockInventory {
 public SavedWeapon[] aspects=new SavedWeapon[0];public UnlockedCard[] arcana=new UnlockedCard[0];public string[] gods=new string[0];public int grasp;
 public string evidence="Permanent unlock flags in the active profile. Gods are confirmed by recorded encounters; unconfirmed gods are excluded. Availability does not guarantee an offer this run.";
}
public class UnlockedCard {public string id,name,traitId,awakening;public int rank,cost,row,column;public bool equipped;}
// Reads selected literal metadata only. No Lua execution or game writes.
static class UnlockReader {
 internal static Dictionary<string,string> Definitions(string path){
  var result=new Dictionary<string,string>();if(!File.Exists(path))return result;string text=File.ReadAllText(path);if(text.Length>8*1024*1024)return result;
  text=Regex.Replace(text,@"--\[\[[\s\S]*?\]\](?:--)?|--[^\r\n]*","");
  foreach(Match start in Regex.Matches(text,@"(?m)^\t([A-Za-z0-9_]+)\s*=\s*\r?\n\t\{")){
   int open=start.Index+start.Length-1,depth=0;foreach(Match token in Regex.Matches(text.Substring(open),@"""(?:\\.|[^""\\])*""|[{}]")){if(token.Value=="{")depth++;if(token.Value=="}"&&--depth==0){result[start.Groups[1].Value]=text.Substring(open,token.Index+1);break;}}
  }return result;
 }
 internal static string Field(string body,string name){var m=Regex.Match(body??"",@"(?m)^\t\t"+Regex.Escape(name)+@"\s*=\s*""([^""]+)""");return m.Success?m.Groups[1].Value:"";}
 static int Cost(string body){var m=Regex.Match(body,@"(?m)^\t\tCost\s*=\s*(\d+)");return m.Success?int.Parse(m.Groups[1].Value):body.Contains("BaseBonusMetaUpgrade")?0:1;}
 internal static readonly string[][] Aspects={
  new[]{"WeaponStaffSwing","BaseStaffAspect","StaffClearCastAspect","StaffSelfHitAspect","StaffRaiseDeadAspect"},
  new[]{"WeaponDagger","DaggerBackstabAspect","DaggerBlockAspect","DaggerHomingThrowAspect","DaggerTripleAspect"},
  new[]{"WeaponTorch","TorchSpecialDurationAspect","TorchDetonateAspect","TorchSprintRecallAspect","TorchAutofireAspect"},
  new[]{"WeaponAxe","AxeRecoveryAspect","AxeArmCastAspect","AxePerfectCriticalAspect","AxeRallyAspect"},
  new[]{"WeaponLob","LobAmmoBoostAspect","LobCloseAttackAspect","LobImpulseAspect","LobGunAspect"},
  new[]{"WeaponSuit","BaseSuitAspect","SuitHexAspect","SuitMarkCritAspect","SuitComboAspect"}};
 internal static UnlockInventory Project(object state,TraitNames names){
  var result=new UnlockInventory();var weapons=HadesSave.Get(state,"WeaponsUnlocked");var list=new List<SavedWeapon>();
  foreach(var family in Aspects){if(!object.Equals(HadesSave.Get(weapons,family[0]),true))continue;for(int i=1;i<family.Length;i++){string aspect=family[i];if(i>1&&!object.Equals(HadesSave.Get(weapons,aspect),true))continue;int rank=1;for(int n=2;n<=5;n++)if(object.Equals(HadesSave.Get(weapons,aspect+n),true))rank++;list.Add(new SavedWeapon{id=family[0],name=names.Name(family[0]),aspectId=aspect,aspectName=names.Name(aspect),aspectRank=rank});}}
  result.aspects=list.ToArray();result.grasp=(int)HadesSave.Number(HadesSave.Get(state,"MaxMetaUpgradeCostCache"));
  var definitions=Definitions(Path.Combine(names.ScriptDirectory,"MetaUpgradeData.lua"));var layout=HadesSave.Ordered(HadesSave.Get(state,"MetaUpgradeCardLayout")).ToArray();var cards=new List<UnlockedCard>();
  foreach(var item in HadesSave.Table(HadesSave.Get(state,"MetaUpgradeState"))){string id=HadesSave.Str(item.Key),body;if(!object.Equals(HadesSave.Get(item.Value,"Unlocked"),true)||!definitions.TryGetValue(id,out body))continue;string trait=Field(body,"TraitName");if(trait.Length==0)continue;var card=new UnlockedCard{id=id,name=names.Name(id),traitId=trait,rank=(int)HadesSave.Number(HadesSave.Get(item.Value,"Level")),cost=Cost(body),equipped=object.Equals(HadesSave.Get(item.Value,"Equipped"),true),awakening=Field(body,"AutoEquipText")};foreach(var row in layout)foreach(var col in HadesSave.Ordered(row.Value))if(HadesSave.Str(col.Value)==id){card.row=(int)(double)row.Key;card.column=(int)(double)col.Key;}cards.Add(card);}
  result.arcana=cards.ToArray();var pickups=HadesSave.Get(state,"LootPickups");result.gods=new[]{"Zeus","Poseidon","Apollo","Hera","Aphrodite","Demeter","Hephaestus","Hestia","Ares"}.Where(g=>HadesSave.Number(HadesSave.Get(pickups,g+"Upgrade"))>0).ToArray();return result;
 }
}
class BuildTarget {public string role,slot,why;public string[] ids;}
class BuildRecipe {
 public string id,title,aspect,style,description,strength,rotation,limit,source;public bool omega;public string[] hammers;public BuildTarget[] targets;
 public override string ToString(){return title;}
}
class PlanStep {public string role,status,target,why;public string[] alternatives;}
class PlanView {public string title,mode,next,adaptation;public SavedWeapon weapon;public UnlockedCard[] cards;public PlanStep[] steps;public string keepsake;public int grasp;}
static class BuildPlanner {
 internal const string CoachInstructions=" SELECTED BUILD: coachJournal.selectedBuild is the player's desired recipe, never proof of ownership. Follow its next target while comparing actual offers, rarity, costs, conditions and replacement losses. ADAPTED targets already have acceptable alternatives: develop those rather than insisting on the original. COMPARE means preserve the current core unless a concrete offered improvement justifies replacement. When the equipped aspect differs, this is a next-run plan; weapon and Arcana changes are pre-run only. Actual saved gear and later explicit player reports take precedence. Plans never guarantee rolls, one-shots or record times. An upgrade to an owned boon changes that boon; it does not add another stacking copy. Compare the displayed NEW value with the CURRENT value. Never add current and new percentages or damage together. Same-name upgrades are incremental improvements, not new acquisitions.";
 internal const string ResearchDate="2026-10-03";
 internal const string SpeedSource="https://mobalytics.gg/hades-2/guides/how-to-speedrun";
 internal const string GuideSource="https://www.leereamsnyder.com/hades-2-build-guide";
 static TraitNames names;internal static TraitNames Names{get{return names??(names=new TraitNames(SaveMemorySync.FindLocalization()));}}
 static readonly Dictionary<string,string> ExtraGods=new Dictionary<string,string>{{"MassiveDamageBoon","Hephaestus"},{"BurnExplodeBoon","Hestia"},{"SlowExAttackBoon","Demeter"},{"FireballManaSpecialBoon","Hestia"},{"FocusLightningBoon","Zeus"},{"OmegaHeraProjectileBoon","Hera"}};
 static BuildTarget T(string role,string slot,string why,params string[] ids){return new BuildTarget{role=role,slot=slot,why=why,ids=ids};}
 internal static readonly BuildRecipe[] Recipes={
  new BuildRecipe{id="skull-burst",title="Explosion / burst",aspect="LobAmmoBoostAspect",style="Burst",description="A burst-damage route using the skull you already own. Build a strong Attack, then add a separate blast on Special.",strength="Short damage windows and clustered enemies.",rotation="Cast to contain enemies, spend skulls, then use Special to retrieve them and trigger a ready blast.",limit="Rank matters. This is an unlocked adaptation, not a guaranteed one-shot or the locked Medea speedrun setup.",source=GuideSource+"#aspect-of-melinoe-skull",hammers=new[]{"LobSpreadShotTrait","LobPulseAmmoCollectTrait"},targets=new[]{T("Main damage","Melee","Build the primary hit before chasing support.","AphroditeWeaponBoon","HeraWeaponBoon","ApolloWeaponBoon"),T("Burst trigger","Secondary","Use the blast when ready; compare recharge and damage on the actual offer.","HephaestusSpecialBoon","ZeusSpecialBoon"),T("Control","Ranged","Keep targets in range for the next burst.","DemeterCastBoon","HeraCastBoon"),T("Blast support","","Optional after a blast core; do not expect it on every offer.","MassiveDamageBoon")}},
  new BuildRecipe{id="momus-omega",title="Omega barrage",aspect="StaffSelfHitAspect",style="Omega",omega=true,description="Layer repeating Omega attacks with Momus, using recovery to keep the sequence going.",strength="Sustained boss damage and overlapping damage zones.",rotation="Place Omega moves where enemies will remain. Reposition or refresh them when the fight moves.",limit="Magick and safe channel time come first. Your owned aspect rank determines echo timing.",source=GuideSource+"#aspect-of-momus-staff",hammers=new[]{"StaffOneWayAttackTrait","StaffTripleShotTrait"},targets=new[]{T("Magick engine","Mana","Secure recovery before buying expensive Omega support.","ApolloManaBoon","HeraManaBoon","PoseidonManaBoon","HestiaManaBoon"),T("Main damage","Melee","Strengthen the Omega attack you can consistently land.","AphroditeWeaponBoon","ApolloWeaponBoon","HeraWeaponBoon"),T("Cast zone","Ranged","Add damage or control where you place the repeating attacks.","ApolloCastBoon","DemeterCastBoon","HeraCastBoon"),T("Omega support","","Take when it supports your actual rotation and Magick supply.","SlowExAttackBoon","PoseidonExCastBoon","OmegaHeraProjectileBoon")}},
  new BuildRecipe{id="flame-swarm",title="Flame swarm",aspect="TorchSpecialDurationAspect",style="Sustained",omega=true,description="Maintain orbiting flames while building damage through Attack and Special together.",strength="Steady pressure while moving around a boss or crowd.",rotation="Keep Omega Special active and weave attacks while staying at a safe distance.",limit="Preserve a strong existing core. A different god or a high-rarity offer can be better than forcing the first target.",source=GuideSource+"#aspect-of-melinoe-flames",hammers=new[]{"TorchExSpecialCountTrait"},targets=new[]{T("Magick engine","Mana","Support repeated Omega Specials.","HeraManaBoon","ApolloManaBoon","HestiaManaBoon","PoseidonManaBoon"),T("Orbiting damage","Secondary","Improve the move this aspect sustains.","HeraSpecialBoon","AphroditeSpecialBoon","ApolloSpecialBoon","ZeusSpecialBoon"),T("Attack support","Melee","Choose a complementary core instead of duplicating a role blindly.","DemeterWeaponBoon","AphroditeWeaponBoon","HestiaWeaponBoon","HeraWeaponBoon"),T("Cast support","Ranged","Choose useful control and check actual curse uptime for Origination.","HeraCastBoon","DemeterCastBoon","HestiaCastBoon")}},
  new BuildRecipe{id="axe-cleaver",title="Axe cleaver",aspect="AxeRecoveryAspect",style="Burst",description="A direct Attack build that invests in the axe's heavy hits and reliable openings.",strength="Strong individual hits with simple damage priorities.",rotation="Use Cast for space and take short attack windows. Avoid committing to the final chop when it is unsafe.",limit="Your base aspect is usable at rank I, but higher ranks improve its damage advantage. Choose this for its playstyle, not a promised record time.",source=GuideSource+"#aspect-of-melinoe-axe",hammers=new[]{"AxeDashAttackTrait","AxeAttackRecoveryTrait"},targets=new[]{T("Main damage","Melee","Large percentage bonuses suit heavy hits; compare range and conditions.","AphroditeWeaponBoon","ApolloWeaponBoon","HeraWeaponBoon"),T("Control","Ranged","Create time to finish attacks.","DemeterCastBoon","HeraCastBoon","HestiaCastBoon"),T("Extra damage","Secondary","Weave a supporting hit between attacks.","ZeusSpecialBoon","HephaestusSpecialBoon","HestiaSpecialBoon")}},
  new BuildRecipe{id="staff-artillery",title="Staff artillery",aspect="BaseStaffAspect",style="Ranged",description="Use your upgraded base staff for a Special-focused route with room to adapt to its hammer.",strength="Ranged pressure and a straightforward primary damage slot.",rotation="Keep space with Cast and use Special consistently. Add Omega Special when the opening and Magick allow it.",limit="This is a sandbox adaptation to your unlocked staff. Switch emphasis if a strong Attack hammer and core arrive.",source=GuideSource+"#aspect-of-melinoe-staff",hammers=new[]{"StaffTripleShotTrait"},targets=new[]{T("Primary special","Secondary","Compare hit frequency, damage, and hammer interaction.","ApolloSpecialBoon","HeraSpecialBoon","PoseidonSpecialBoon","ZeusSpecialBoon"),T("Magick engine","Mana","Useful if Omega Special becomes a major part of the rotation.","ApolloManaBoon","HeraManaBoon","HestiaManaBoon"),T("Control","Ranged","Keep a safe space for ranged damage.","DemeterCastBoon","HeraCastBoon","HestiaCastBoon")}},
  new BuildRecipe{id="blades-pressure",title="Blades pressure",aspect="DaggerBackstabAspect",style="Fast hits",description="Combine short attack bursts with a complementary Special. Use the base blades without waiting on a hidden aspect.",strength="Mobile close-range damage.",rotation="Use short attack sequences and weave Special while repositioning.",limit="Close range is a tradeoff. Choose control or survival over a marginal damage gain when needed.",source=GuideSource+"#aspect-of-melinoe-blades",hammers=new string[0],targets=new[]{T("Attack engine","Melee","Compare frequent-hit effects with conditional percentage damage.","AphroditeWeaponBoon","PoseidonWeaponBoon","HestiaWeaponBoon","HeraWeaponBoon"),T("Weave special","Secondary","Add a second damage source in your rotation.","HephaestusSpecialBoon","ZeusSpecialBoon","HeraSpecialBoon"),T("Control","Ranged","Keep an escape lane and support actual curse uptime.","DemeterCastBoon","HeraCastBoon","HestiaCastBoon")}},
  new BuildRecipe{id="medea-speed",title="Medea speed burst",aspect="LobCloseAttackAspect",style="Speedrun",description="A leading community speedrun route centered on the Attack-to-Special cycle.",strength="Fast clears and concentrated burst.",rotation="Load Attack, release it through Special, repeat.",limit="A speedrun route still needs suitable offers and execution. It does not guarantee leaderboard times.",source=SpeedSource,hammers=new[]{"LobPulseAmmoCollectTrait"},targets=new[]{T("Blitz special","Secondary","Community opening priority.","ZeusSpecialBoon"),T("Attack damage","Melee","Choose a useful percentage core.","HeraWeaponBoon","AphroditeWeaponBoon","ApolloWeaponBoon"),T("Magick if needed","Mana","Add recovery when an Omega hammer makes it useful.","HeraManaBoon","ApolloManaBoon")}},
  new BuildRecipe{id="charon-speed",title="Charon cast eruption",aspect="AxeArmCastAspect",style="Speedrun",omega=true,description="A community speed route built around detonating Cast with Omega Special.",strength="Large damage zones.",rotation="Place Cast, then hit it with Omega Special.",limit="Fund the Magick cost before leaning on repeated detonations.",source=SpeedSource,hammers=new string[0],targets=new[]{T("Cast damage","Ranged","Build the detonation zone.","ApolloCastBoon","PoseidonCastBoon"),T("Special damage","Secondary","Support the trigger move.","ApolloSpecialBoon","PoseidonSpecialBoon","HeraSpecialBoon"),T("Magick engine","Mana","Keep the cycle sustainable.","ApolloManaBoon","PoseidonManaBoon","HeraManaBoon")}},
  new BuildRecipe{id="moros-speed",title="Moros chain blasts",aspect="TorchDetonateAspect",style="Speedrun",omega=true,description="A community speed route linking the flames' attacks and specials.",strength="Dense area damage.",rotation="Keep attacks and specials interacting while maintaining Magick.",limit="Close-range execution and recovery are part of the setup.",source=SpeedSource,hammers=new string[0],targets=new[]{T("Special engine","Secondary","Community opening priority.","HeraSpecialBoon"),T("Magick engine","Mana","Fuel the damage cycle.","HeraManaBoon","ApolloManaBoon"),T("Omega support","","Add after recovery is stable.","OmegaHeraProjectileBoon"),T("Attack control","Melee","Use a complementary curse.","DemeterWeaponBoon","HestiaWeaponBoon")}}
 };
 internal static string God(string id){string god;if(ExtraGods.TryGetValue(id,out god))return god;return new[]{"Zeus","Poseidon","Apollo","Hera","Aphrodite","Demeter","Hephaestus","Hestia","Ares"}.FirstOrDefault(g=>id.StartsWith(g,StringComparison.Ordinal))??"";}
 internal static string[] AvailableIds(BuildTarget t,SavedBuild b){return t.ids.Where(id=>Names.Name(id)!=id&&(b.unlocks.gods??new string[0]).Contains(God(id))).ToArray();}
 internal static BuildRecipe[] Available(SavedBuild b){if(b==null||b.unlocks==null)return new BuildRecipe[0];return Recipes.Where(r=>b.unlocks.aspects.Any(a=>a.aspectId==r.aspect)&&r.targets.All(t=>AvailableIds(t,b).Length>0)).OrderByDescending(r=>Matches(r,b)).ThenByDescending(r=>b.unlocks.aspects.First(a=>a.aspectId==r.aspect).aspectRank).ToArray();}
 internal static bool Matches(BuildRecipe recipe,SavedBuild b){return b!=null&&b.weapon!=null&&b.weapon.aspectId==recipe.aspect;}
 internal static BuildRecipe Selected(SavedBuild b,CoachJournal j){return b==null||j.buildProfile!=b.profile?null:Available(b).FirstOrDefault(r=>r.id==j.buildId);}
 internal static void Choose(BuildRecipe r,SavedBuild b){if(r==null||!Available(b).Any(x=>x.id==r.id))throw new Exception("This build is not confirmed available in the current profile.");var j=RunLab.Load();j.buildId=r.id;j.buildProfile=b.profile;RunLab.Save(j);Diagnostics.Log("Build plan selected: "+r.id+"; advice only, no gear recorded.");}
 internal static void Clear(){var j=RunLab.Load();j.buildId=j.buildProfile="";RunLab.Save(j);}
 internal static string SelectCommand(string text,SavedBuild b){string command=ScreenSignals.Clean(text);string prefix=new[]{"use build ","switch build to ","choose build "}.FirstOrDefault(p=>command.StartsWith(p));if(prefix==null)return null;string name=command.Substring(prefix.Length);var recipe=Available(b).FirstOrDefault(r=>ScreenSignals.Clean(r.title)==name||ScreenSignals.Clean(r.id.Replace('-',' '))==name);if(recipe==null)return "That build is not confirmed available. Open Sandbox to choose an unlocked route.";Choose(recipe,b);return "Selected "+recipe.title+". "+View(recipe,b).next;}
 internal static LabReply Brief(SavedBuild b){var r=Selected(b,RunLab.Load());if(r==null)return null;var v=View(r,b);return new LabReply{brief="Your selected route is "+r.title+". "+v.adaptation,focus=Matches(r,b)?r.rotation:"Before the next run: "+v.weapon.name+", "+v.weapon.aspectName+" at your owned rank "+v.weapon.aspectRank+". Your current run keeps its actual setup.",nextTarget=v.next,watchFor=r.limit};}
 internal static UnlockedCard[] Deck(BuildRecipe r,SavedBuild b){
  if(b==null||b.unlocks==null)return new UnlockedCard[0];var u=b.unlocks;var selected=new List<UnlockedCard>();int total=0;
  string[] priority=r.omega?new[]{"LastStand","MagicCrit","ChanneledCast","CastBuff","StatusVulnerability","BonusHealth","ScreenReroll","RarityBoost","HealthRegen","BonusDodge","SprintShield","MetaToRunUpgrade","LowManaDamageBonus"}:new[]{"LastStand","LowManaDamageBonus","CastBuff","StatusVulnerability","ScreenReroll","RarityBoost","HealthRegen","BonusHealth","BonusDodge","SprintShield","MetaToRunUpgrade","ChanneledCast"};
  foreach(string id in priority){var c=u.arcana.FirstOrDefault(a=>a.id==id&&a.cost>0);if(c!=null&&total+c.cost<=u.grasp){selected.Add(c);total+=c.cost;}}
  foreach(var c in u.arcana.Where(a=>a.cost==0)){bool active=c.id=="MaxHealthPerRoom"?Enumerable.Range(1,5).All(n=>selected.Any(a=>a.cost==n)):c.id=="SorceryRegenUpgrade"?c.row>0&&selected.Any(a=>a.row>0&&Math.Abs(a.row-c.row)<=1&&Math.Abs(a.column-c.column)<=1):c.id=="BonusRarity"?selected.Count>0&&selected.GroupBy(a=>a.cost).All(g=>g.Count()<=2):false;if(active)selected.Add(c);}
  return selected.ToArray();
 }
 internal static string CardRole(string id){switch(id){case "LastStand":return "Death Defiance reserve";case "MagicCrit":return "Omega-combo damage";case "ChanneledCast":return "faster channeling";case "CastBuff":return "damage against foes in Cast";case "StatusVulnerability":return "damage with two Olympian curses active";case "ScreenReroll":return "reroll boon choices";case "RarityBoost":return "better boon rarity odds";case "HealthRegen":return "recovery between locations";case "BonusHealth":return "Life and Magick capacity";case "BonusDodge":return "safer, quicker Cast";case "SprintShield":return "dash and sprint support";case "MetaToRunUpgrade":return "turn minor rewards into major rewards";case "LowManaDamageBonus":return "normal Attack/Special damage below full Magick";case "SorceryRegenUpgrade":return "Hex charge";case "MaxHealthPerRoom":return "Life and Magick growth";case "BonusRarity":return "Duo boon odds";default:return "check its installed in-game description";}}
 internal static string EvidenceStamp(RunRecord run){var last=run.events.LastOrDefault(e=>(e.updates??new BuildUpdate[0]).Any(u=>u.evidence!="game_state"&&new[]{"acquired","equipped","correction","preference"}.Contains(u.category)));return last==null?"":last.time;}
 static string Reported(string[] ids,SavedBuild b){var run=RunMemory.Load();DateTime checkpoint;if(run.gameState==null||run.gameState.sourceRun!=b.sourceRun||!DateTime.TryParse(b.savedAt,out checkpoint))return "";var updates=run.events.Where(e=>{DateTime t;return DateTime.TryParse(e.time,out t)&&t.ToUniversalTime()>checkpoint.ToUniversalTime();}).SelectMany(e=>e.updates??new BuildUpdate[0]).Reverse().ToArray();foreach(var u in updates){var matching=ids.Where(id=>(" "+OfferMemory.Identity(u.fact)+" ").Contains(" "+OfferMemory.Identity(Names.Name(id))+" ")).ToArray();if(matching.Length!=1)continue;if(new[]{"correction","uncertain"}.Contains(u.category))return "";if(new[]{"acquired","equipped"}.Contains(u.category)&&new[]{"player","visible"}.Contains(u.evidence))return matching[0];}return "";}
 static string CoreReport(string slot,SavedBuild b){string suffix=slot=="Melee"?"WeaponBoon":slot=="Secondary"?"SpecialBoon":slot=="Ranged"?"CastBoon":slot=="Mana"?"ManaBoon":"";return suffix.Length==0?"":Reported(new[]{"Zeus","Poseidon","Apollo","Hera","Aphrodite","Demeter","Hephaestus","Hestia","Ares"}.Select(g=>g+suffix).Where(id=>Names.Name(id)!=id).ToArray(),b);}
 static string CoreId(string slot,SavedBuild b){string report=CoreReport(slot,b);var old=(b.owned??new SavedTrait[0]).FirstOrDefault(t=>t.slot==slot&&t.category=="trait");return report.Length>0?report:old==null?"":old.id;}
 internal static BuildTarget[] EffectiveTargets(BuildRecipe r,SavedBuild b){var list=r.targets.ToList();if(Matches(r,b)&&(CoreId("Melee",b)=="HephaestusWeaponBoon"||CoreId("Secondary",b)=="HephaestusSpecialBoon")&&b.unlocks.gods.Contains("Hephaestus")&&!list.Any(t=>t.ids.Contains("MassiveDamageBoon")))list.Add(T("Support your blast","","Adapted to the blast already equipped. Develop it before forcing a replacement.","MassiveDamageBoon"));return list.ToArray();}
 internal static PlanView View(BuildRecipe r,SavedBuild b){
  var v=new PlanView{title=r.title,weapon=b.unlocks.aspects.First(a=>a.aspectId==r.aspect),cards=Deck(r,b),grasp=b.unlocks.grasp,mode=Matches(r,b)?"Guiding the equipped aspect":"Next-run setup · equipped aspect differs"};var steps=new List<PlanStep>();var owned=Matches(r,b)?b.owned??new SavedTrait[0]:new SavedTrait[0];
  var targets=EffectiveTargets(r,b);foreach(var t in targets){var ids=AvailableIds(t,b);var hit=owned.FirstOrDefault(a=>ids.Contains(a.id));string reported=Matches(r,b)?Reported(ids,b):"";string newerCore=Matches(r,b)?CoreReport(t.slot,b):"";if(newerCore.Length>0&&!ids.Contains(newerCore))hit=null;var occupied=t.slot.Length==0?null:owned.FirstOrDefault(a=>a.slot==t.slot&&a.category=="trait");if(newerCore.Length>0)occupied=new SavedTrait{name=Names.Name(newerCore)};string state=reported.Length>0?"REPORTED":hit!=null?(hit.id==ids[0]?"OWNED":"ADAPTED"):occupied!=null?"COMPARE":"SEEK";steps.Add(new PlanStep{role=t.role,status=state,target=reported.Length>0?Names.Name(reported):hit!=null?hit.name+(!string.IsNullOrEmpty(hit.rarity)?" ("+hit.rarity+")":""):Names.Name(ids[0]),alternatives=ids.Skip(1).Select(Names.Name).ToArray(),why=reported.Length>0?"Recorded after the checkpoint from a player report or confirmed visual pickup. Autosave has not caught up; no repeat confirmation needed.":hit!=null?"Confirmed equipped in the save. "+t.why:occupied!=null?"You have "+occupied.name+". Keep it unless an actual offer wins on damage, conditions and lost synergies.":t.why});}
  v.steps=steps.ToArray();var pending=steps.FirstOrDefault(s=>s.status=="SEEK");v.next=!Matches(r,b)?"Equip the listed weapon and aspect before a new run. Current-run coaching continues from your actual equipment.":pending!=null?pending.role+": look for "+pending.target+" or a listed alternative.":steps.Any(s=>s.status=="COMPARE")?"Your slots are filled. Compare support and upgrades before replacing a strong core.":"Core targets are equipped. Prioritize efficient upgrades, compatible support and survival.";
  v.adaptation=!Matches(r,b)?"Weapon and Arcana changes are pre-run advice. Selecting this route does not equip or acquire anything.":steps.Any(s=>s.status=="ADAPTED")?"An accepted alternative is already equipped. The route now builds around it; the original target is optional.":steps.Any(s=>s.status=="COMPARE")?"Your actual core differs from the recipe. Preserve its investment and compare the next real offer; do not force a replacement.":"Progress updates from your game-save checkpoint. Boons offered on screen are never counted as owned.";
  int nextIndex=Array.FindIndex(v.steps,s=>s.status=="SEEK");var nextTarget=nextIndex<0?null:targets[nextIndex];var god=nextTarget==null?"":God(AvailableIds(nextTarget,b)[0]);var keepsake=(Matches(r,b)?KeepsakePlanner.Candidates(b):b.keepsakes??new SavedKeepsake[0]).FirstOrDefault(k=>k.id=="Force"+god+"BoonKeepsake");v.keepsake=nextTarget==null?"Your core slots are covered. Use the keepsake-menu coach to compare currently available support and protection.":keepsake==null?"No available owned keepsake confirms a way to target the next god. Use the keepsake-menu coach for your available alternatives.":keepsake.name+" · increases access to "+god+". Only swap at an eligible keepsake menu; the menu's locks take precedence.";return v;
 }
 internal static object Context(SavedBuild b,CoachJournal j){var r=Selected(b,j);if(r==null)return null;var v=View(r,b);return new{recipe=r.id,r.title,r.description,r.strength,r.rotation,r.limit,source=r.source,researched=ResearchDate,actualAspectMatches=Matches(r,b),plan=v};}
 internal static string Describe(BuildRecipe r,SavedBuild b){var v=View(r,b);var s=new StringBuilder();s.AppendLine(r.description+"\r\n");s.AppendLine("BEST AT\r\n"+r.strength+"\r\n");s.AppendLine("YOUR SETUP\r\n"+v.weapon.name+" · "+v.weapon.aspectName+" · owned rank "+v.weapon.aspectRank+"\r\n"+v.mode+"\r\n");s.AppendLine("HOW TO PLAY\r\n"+r.rotation+"\r\n");s.AppendLine("NEXT MOVE\r\n"+v.next+"\r\n"+v.adaptation+"\r\n");s.AppendLine("BOON ROUTE · SAVE + CONFIRMED RECENT REPORTS");foreach(var step in v.steps){s.AppendLine(step.status+"  ·  "+step.role+" — "+step.target);s.AppendLine(step.why);if(step.alternatives.Length>0)s.AppendLine("Alternatives: "+string.Join(", ",step.alternatives));s.AppendLine();}
  s.AppendLine("ARCANA TO EQUIP BEFORE THE RUN · "+v.cards.Sum(c=>c.cost)+" / "+v.grasp+" GRASP");foreach(var c in v.cards)s.AppendLine(c.name+" · rank "+c.rank+" · "+c.cost+" Grasp · "+CardRole(c.id)+(c.cost==0?" (awakening satisfied by this deck)":""));s.AppendLine("\r\nThis uses only unlocked cards and your current ranks. It is a recommended deck; the active build remains whatever the game save reports.");s.AppendLine("\r\nKEEPSAKE\r\n"+v.keepsake);if(r.hammers.Length>0)s.AppendLine("\r\nHAMMERS TO CONSIDER\r\n"+string.Join(", ",r.hammers.Select(Names.Name))+". Optional offer-dependent upgrades; verify compatibility and Magick cost in the actual menu.");s.AppendLine("\r\nTRADEOFF\r\n"+r.limit);s.AppendLine("\r\nCOMMUNITY REFERENCE · researched "+ResearchDate+"\r\n"+r.source+"\r\nUnlock-constrained advice, not a verified record build. Installed game text and current offers take precedence over older guides.");return s.ToString();}
}
class SandboxPanel : UserControl {
 readonly TrainingPanel training;readonly BuildPickerPanel picker;readonly Panel pages;
 internal RichTextBox Result{get{return training.Result;}}
 internal SandboxPanel(Func<string,bool,System.Threading.Tasks.Task> execute,Action<string> ask){Dock=DockStyle.Fill;BackColor=Theme.Bg;ForeColor=Theme.Text;Padding=new Padding(20);pages=new Panel{Dock=DockStyle.Fill};var tabs=Theme.Flow();tabs.Dock=DockStyle.Top;var buildButton=Theme.Action("Pick your build","layers","Explore routes compatible with your unlocked equipment.",(s,e)=>ShowPage(false));var trainingButton=Theme.Action("Run check-ins","flask","Create a local briefing, compare progress, or review the last attempt.",(s,e)=>ShowPage(true));tabs.Controls.Add(buildButton);tabs.Controls.Add(trainingButton);Controls.Add(pages);Controls.Add(tabs);training=new TrainingPanel(execute,ask){Padding=new Padding(0,12,0,0)};picker=new BuildPickerPanel(ask);pages.Controls.Add(training);pages.Controls.Add(picker);ShowPage(false);}
 void ShowPage(bool lab){if(training==null||picker==null)return;training.Visible=lab;picker.Visible=!lab;(lab?(Control)training:picker).BringToFront();}
 internal void RefreshBuild(){picker.RefreshBuild();}
}
}
