using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Linq;
using System.Windows.Forms;
namespace GameCoach {
// Each detail view scrolls as a whole. No text panel nested inside another
// scrolling panel, fixed-height descriptions, or programmatic scroll jumps.
class BuildPickerPanel : UserControl {
 readonly ComboBox filter;readonly CheckBox equipped;readonly Label inventory,active;readonly ListBox builds;readonly Panel content,detailScroll;readonly TableLayoutPanel detail;readonly Button choose;Button clear;readonly FlowLayoutPanel tabs;readonly Action<string> discuss;
 SavedBuild snapshot;string stamp="",page="Overview";bool refreshing;TableLayoutPanel columns;bool narrow;
 internal BuildPickerPanel(Action<string> ask){
  discuss=ask;Dock=DockStyle.Fill;BackColor=Theme.Bg;ForeColor=Theme.Text;Padding=new Padding(0,10,0,0);
  var outer=Theme.Stack();outer.Dock=DockStyle.Fill;outer.AutoSize=false;Controls.Add(outer);Theme.ScrollLayout(this,outer,540);
  var head=Theme.Stack();Theme.Row(head,Theme.Heading("Pick your build",24));var sub=Theme.Copy("A plan for your unlocks. A route that changes with your run.");Theme.Row(head,sub);Theme.Row(outer,head);
  inventory=Theme.Copy("");inventory.Font=new Font("Segoe UI",9);Theme.Row(outer,inventory);
  active=Theme.Copy("");active.ForeColor=Theme.Mint;active.Font=new Font("Segoe UI Semibold",10);Theme.Row(outer,active);
  var filters=Theme.Flow();filter=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=(int)(155*Theme.Scale),AccessibleName="Build style filter"};filter.Items.AddRange(new[]{"All playstyles","Burst","Omega","Sustained","Ranged","Fast hits","Speedrun"});filter.SelectedIndex=0;filters.Controls.Add(filter);
  equipped=new CheckBox{AutoSize=true,Text="My equipped aspect",ForeColor=Theme.Muted,Margin=new Padding(10,6,12,0),AccessibleName="Equipped aspect only"};filters.Controls.Add(equipped);filters.Controls.Add(Theme.Action("Refresh unlocks","refresh","Read newly saved unlocks from Hades II. Only unlocked routes are listed.",(s,e)=>{SaveMemorySync.Refresh(true);RefreshBuild(true);}));Theme.Row(outer,filters);
  columns=new TableLayoutPanel{ColumnCount=2,RowCount=1,Dock=DockStyle.Fill,Margin=new Padding(0)};columns.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,30));columns.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,70));columns.RowStyles.Add(new RowStyle(SizeType.Percent,100));int row=outer.RowCount++;outer.RowStyles.Add(new RowStyle(SizeType.Percent,100));outer.Controls.Add(columns,0,row);
  builds=new ListBox{Dock=DockStyle.Fill,BackColor=Theme.Bg,ForeColor=Theme.Text,BorderStyle=BorderStyle.None,DrawMode=DrawMode.OwnerDrawFixed,ItemHeight=(int)(94*Theme.Scale),IntegralHeight=false,Margin=new Padding(0,0,14,0),AccessibleName="Unlocked build routes"};builds.DrawItem+=DrawBuild;builds.SelectedIndexChanged+=(s,e)=>{if(!refreshing)Render();};columns.Controls.Add(builds,0,0);
  content=new Panel{Dock=DockStyle.Fill,BackColor=Theme.Bg,Margin=new Padding(0)};columns.Controls.Add(content,1,0);
  var right=Theme.Stack();right.Dock=DockStyle.Fill;right.AutoSize=false;content.Controls.Add(right);
  var actions=Theme.Flow();choose=Theme.Action("Use this build","check","Guide the current run if your aspect matches, or save the route for a matching setup. Nothing is equipped automatically.",(s,e)=>{var r=builds.SelectedItem as BuildRecipe;if(r==null)return;BuildPlanner.Choose(r,snapshot);RefreshBuild(true);});choose.AccessibleName="Use selected build plan";actions.Controls.Add(choose);actions.Controls.Add(Theme.Action("Explain build","mic","Ask the cloud coach about this route with your equipment. This does not select the route; it uses API credits.",(s,e)=>{var r=builds.SelectedItem as BuildRecipe;if(r!=null)discuss("Explain the sandbox build '"+r.title+"' for my actual equipment and unlocks. Give one useful next step. This question does not select or equip it.");}));actions.Controls.Add(clear=Theme.Action("Stop guidance","close","Remove the selected build plan and its target markers. Your run memory and general recommendations stay available.",(s,e)=>{BuildPlanner.Clear();RefreshBuild(true);}));Theme.Row(right,actions);
  tabs=Theme.Flow();foreach(string name in new[]{"Overview","Boon roadmap","Pre-run setup"}){string tab=name;var tabButton=Theme.Button(name,(s,e)=>{page=tab;Render();});Theme.Hint(tabButton,name=="Overview"?"Read the build strategy, tradeoffs and next step.":name=="Boon roadmap"?"See targets, alternatives and which pieces are already recorded.":"See the unlocked weapon, keepsake and Arcana to equip before starting.");tabs.Controls.Add(tabButton);}Theme.Row(right,tabs);
  detailScroll=new Panel{Dock=DockStyle.Fill,AutoScroll=true,BackColor=Theme.Bg,Margin=new Padding(0),AccessibleName="Build details"};detail=Theme.Stack();detail.Padding=new Padding(0,0,10,8);detailScroll.Controls.Add(detail);row=right.RowCount++;right.RowStyles.Add(new RowStyle(SizeType.Percent,100));right.Controls.Add(detailScroll,0,row);
  filter.SelectedIndexChanged+=(s,e)=>RefreshBuild(true);equipped.CheckedChanged+=(s,e)=>RefreshBuild(true);VisibleChanged+=(s,e)=>{if(Visible){SaveMemorySync.Refresh();RefreshBuild(true);}};
  SizeChanged+=(s,e)=>Responsive();Theme.Hint(filter,"Filter compatible build routes by playstyle.");Theme.Hint(equipped,"Limit the list to the aspect currently equipped in the latest game save.");Theme.StyleInputs(this);choose.BackColor=Theme.Mint;choose.ForeColor=Theme.Bg;RefreshBuild(true);
 }
 void Responsive(){bool value=ClientSize.Width<(int)(570*Theme.Scale);if(value==narrow)return;narrow=value;columns.SuspendLayout();columns.Controls.Clear();columns.RowStyles.Clear();columns.ColumnStyles.Clear();columns.ColumnCount=narrow?1:2;columns.RowCount=narrow?2:1;columns.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,narrow?100:30));if(!narrow)columns.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,70));if(narrow)columns.RowStyles.Add(new RowStyle(SizeType.Absolute,110*Theme.Scale));columns.RowStyles.Add(new RowStyle(SizeType.Percent,100));builds.Margin=new Padding(0,0,narrow?0:14,narrow?10:0);columns.Controls.Add(builds,0,0);columns.Controls.Add(content,narrow?0:1,narrow?1:0);columns.ResumeLayout(true);}
 void DrawBuild(object sender,DrawItemEventArgs e){if(e.Index<0)return;var r=(BuildRecipe)builds.Items[e.Index];bool selected=(e.State&DrawItemState.Selected)!=0;var box=new Rectangle(e.Bounds.X,e.Bounds.Y,e.Bounds.Width-2,e.Bounds.Height-(int)(8*Theme.Scale));using(var bg=new SolidBrush(selected?Color.FromArgb(29,58,52):Theme.Card))e.Graphics.FillRectangle(bg,box);using(var pen=new Pen(selected?Theme.Mint:Theme.Line))e.Graphics.DrawRectangle(pen,box);int p=(int)(12*Theme.Scale);var a=snapshot==null?null:snapshot.unlocks.aspects.FirstOrDefault(w=>w.aspectId==r.aspect);var flags=TextFormatFlags.EndEllipsis|TextFormatFlags.NoPadding;
  using(var small=new Font("Segoe UI",9))using(var heading=new Font("Segoe UI Semibold",11)){TextRenderer.DrawText(e.Graphics,r.style.ToUpperInvariant()+(BuildPlanner.Matches(r,snapshot)?"  ·  EQUIPPED":""),small,new Rectangle(box.X+p,box.Y+p,box.Width-p*2,(int)(19*Theme.Scale)),selected?Theme.Mint:Theme.Muted,flags);TextRenderer.DrawText(e.Graphics,r.title,heading,new Rectangle(box.X+p,box.Y+p+(int)(22*Theme.Scale),box.Width-p*2,(int)(23*Theme.Scale)),Theme.Text,flags);TextRenderer.DrawText(e.Graphics,a==null?"":a.name,small,new Rectangle(box.X+p,box.Y+p+(int)(48*Theme.Scale),box.Width-p*2,(int)(19*Theme.Scale)),Theme.Gold,flags);}e.DrawFocusRectangle();
 }
 TableLayoutPanel Card(string eyebrow,string title,string text,Color accent){var card=Theme.Stack();card.BackColor=Theme.Card;card.Padding=new Padding((int)(16*Theme.Scale));card.Paint+=(s,e)=>{using(var pen=new Pen(Theme.Line))e.Graphics.DrawRectangle(pen,0,0,card.Width-1,card.Height-1);using(var b=new SolidBrush(accent))e.Graphics.FillRectangle(b,0,0,3,card.Height);};if(eyebrow.Length>0){var label=Theme.Copy(eyebrow);label.Font=new Font("Segoe UI Semibold",9);label.ForeColor=accent;Theme.Row(card,label);}if(title.Length>0)Theme.Row(card,Theme.Heading(title,title.Length>65?14:18));if(text.Length>0)Theme.Row(card,Theme.Copy(text));Theme.Row(detail,card);return card;}
 void Render(){
  if(detail==null)return;detailScroll.SuspendLayout();detail.SuspendLayout();while(detail.Controls.Count>0){var old=detail.Controls[0];detail.Controls.Remove(old);old.Dispose();}detail.RowStyles.Clear();detail.RowCount=0;foreach(Button b in tabs.Controls){b.ForeColor=b.Text==page?Theme.Mint:Theme.Muted;b.FlatAppearance.BorderColor=b.Text==page?Theme.Mint:Theme.Line;}
  var r=builds.SelectedItem as BuildRecipe;choose.Enabled=r!=null;var selected=BuildPlanner.Selected(snapshot,RunLab.Load());clear.Enabled=selected!=null;if(r==null){Card("YOUR UNLOCKS","No matching routes","Try a different playstyle or turn off the equipped-aspect filter. Refresh after the game saves a new unlock.",Theme.Gold);}
  else{var v=BuildPlanner.View(r,snapshot);bool current=BuildPlanner.Matches(r,snapshot),usingThis=selected!=null&&selected.id==r.id;choose.Text=usingThis?"Following this build":current?"Guide this run":"Save for next run";choose.Enabled=!usingThis;
   if(page=="Overview"){
    Card(r.style.ToUpperInvariant()+"  /  "+(current?"READY FOR YOUR SETUP":"NEXT-RUN ROUTE"),r.title,r.description,Theme.Gold);
    var progress=Card("YOUR NEXT MOVE",v.next,v.adaptation,Theme.Mint);int done=v.steps.Count(s=>new[]{"OWNED","ADAPTED","REPORTED"}.Contains(s.status));Theme.Row(progress,new RouteProgress(done,v.steps.Length));
    Card("PLAY THE ROUTE",r.strength,r.rotation,Theme.Line);
    Card("ON YOUR SCREEN","A target, right where you choose","Select this build to enable a marker beside matching boons and useful door rewards. The corner coach still compares the actual offers. Markers adapt to saved pickups and confirmed reports.",Theme.Mint);
    Card("TRADEOFF", "",r.limit,Theme.Gold);
    var source=Card("COMMUNITY REFERENCE","", "Adapted to your unlocked equipment · researched "+BuildPlanner.ResearchDate+". Current game text takes precedence over older guides.",Theme.Line);var link=new LinkLabel{AutoSize=true,Text="Read the build reference ↗",LinkColor=Theme.Mint,ActiveLinkColor=Theme.Gold};link.LinkClicked+=(s,e)=>System.Diagnostics.Process.Start(r.source);Theme.Row(source,link);
   }else if(page=="Boon roadmap"){
    Card("FOLLOW THE OPPORTUNITIES",r.title,"Start with the missing engine. Keep strong alternatives you already have; compare replacements against what you would lose.",Theme.Gold);
    int n=0;foreach(var step in v.steps){n++;string state=step.status=="OWNED"?"EQUIPPED":step.status=="ADAPTED"?"ALTERNATIVE EQUIPPED":step.status=="REPORTED"?"RECORDED · AWAITING CHECKPOINT":step.status=="COMPARE"?"KEEP OR COMPARE":"LOOK FOR";var card=Card(n.ToString("00")+"  /  "+step.role.ToUpperInvariant()+"  /  "+state,step.target,step.why,step.status=="SEEK"?Theme.Gold:Theme.Mint);if(step.alternatives.Length>0)Theme.Row(card,Theme.Copy("Also works: "+string.Join(" · ",step.alternatives)));}
    if(r.hammers.Length>0)Card("OPTIONAL HAMMERS","Weapon upgrades",string.Join(" · ",r.hammers.Select(BuildPlanner.Names.Name))+". Judge the actual offer and its Magick costs.",Theme.Gold);
   }else{
    Card("EQUIP BEFORE YOU GO",v.weapon.name,v.weapon.aspectName+" · owned rank "+v.weapon.aspectRank+"\r\n"+(current?"Matches your equipped aspect.":"Select this setup in game before your next run."),Theme.Gold);
    Card("KEEPSAKE","Open the right opportunity",v.keepsake,Theme.Mint);
    Card("ARCANA DECK",v.cards.Sum(c=>c.cost)+" / "+v.grasp+" Grasp","Only unlocked cards at your owned ranks. Equip these in game before the run; this plan does not change your active cards.",Theme.Gold);
    foreach(var c in v.cards)Card(c.cost+" GRASP  ·  RANK "+c.rank+(c.equipped?"  ·  CURRENTLY EQUIPPED":""),c.name,BuildPlanner.CardRole(c.id)+(c.cost==0?" · awakening satisfied by this recommended deck":""),c.equipped?Theme.Mint:Theme.Line);
   }
  }detail.ResumeLayout(true);detailScroll.AutoScrollPosition=Point.Empty;detailScroll.ResumeLayout(true);Theme.Reflow(detail);
 }
 internal void RefreshBuild(bool force=false){if(builds==null||filter==null||equipped==null)return;var run=RunMemory.Load();var b=run.gameState;var j=RunLab.Load();string current=(b==null?"":b.profile+":"+b.fingerprint+":"+b.projectionVersion)+":"+j.buildId+":"+run.events.Count;if(!force&&stamp==current)return;stamp=current;snapshot=b;string prior=(builds.SelectedItem as BuildRecipe)==null?"":((BuildRecipe)builds.SelectedItem).id;refreshing=true;builds.BeginUpdate();builds.Items.Clear();var available=BuildPlanner.Available(b);foreach(var r in available.Where(r=>(filter.SelectedIndex==0||r.style==filter.Text)&&(!equipped.Checked||BuildPlanner.Matches(r,b))))builds.Items.Add(r);var selected=BuildPlanner.Selected(b,j);var retain=builds.Items.Cast<BuildRecipe>().FirstOrDefault(r=>r.id==prior)??builds.Items.Cast<BuildRecipe>().FirstOrDefault(r=>selected!=null&&r.id==selected.id)??builds.Items.Cast<BuildRecipe>().FirstOrDefault();if(retain!=null)builds.SelectedItem=retain;builds.EndUpdate();refreshing=false;
  inventory.Text=b==null||b.unlocks==null?"Waiting for a valid Hades II save to confirm your unlocks.":b.unlocks.aspects.Length+" aspects   ·   "+b.unlocks.arcana.Length+" Arcana   ·   "+b.unlocks.grasp+" Grasp   ·   "+available.Length+" routes available";
  active.Text=selected==null?"◇  Explore a route, then select it to enable build guidance.":"◇  "+selected.title+"  ·  "+(BuildPlanner.Matches(selected,b)?"Guiding your current setup":"Saved for the matching setup");Render();Responsive();
 }
}
class RouteProgress : Control {
 readonly int done,total;internal RouteProgress(int value,int count){done=value;total=count;Height=(int)(32*Theme.Scale);DoubleBuffered=true;AccessibleName=done+" of "+total+" route targets recorded";}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);int gap=6,w=Math.Max(1,(Width-gap*Math.Max(0,total-1))/Math.Max(1,total));for(int i=0;i<total;i++)using(var b=new SolidBrush(i<done?Theme.Mint:Theme.Line))e.Graphics.FillRectangle(b,i*(w+gap),0,w,5);using(var f=new Font("Segoe UI",9))TextRenderer.DrawText(e.Graphics,done+" of "+total+" route targets recorded",f,new Rectangle(0,10,Width,Height-10),Theme.Muted,TextFormatFlags.NoPadding);}
}
}
