using System;using System.Drawing;using System.Windows.Forms;using System.Text.RegularExpressions;
namespace GameCoach {
static class AppCredits { internal const string Creator="Caganmiller",Email="caganmiller@gmail.com",MailTo="mailto:caganmiller@gmail.com",ShareCredit="Game Coach by Caganmiller"; }
static class GuidePages {
 static TableLayoutPanel Layout(Panel page,string title,string subtitle){var stack=Theme.Stack();page.Controls.Add(stack);Theme.Row(stack,Theme.Heading(title,25));Theme.Row(stack,Theme.Copy(subtitle));return stack;}
 static string Number(TableLayoutPanel stack,string title){int n=stack.Tag is int?(int)stack.Tag:0;stack.Tag=++n;return n+". "+Regex.Replace(title,@"^\d+\s*(?:/\s*|[.]\s*|\s+)","");}
 static void Card(TableLayoutPanel stack,string title,string text){var card=Theme.Section(Number(stack,title));Theme.Row(card,Theme.Copy(text));Theme.Row(stack,card);}
 internal static Control HowTo(){return Tabs("How to use","Everything you need to start, play and share.",new[]{"Using Game Coach","How to install"},new[]{UsingGuide(),Install()});}
 static Control UsingGuide(){var page=Theme.Page();var stack=Layout(page,"Your next run","A companion you can leave minimized. You play; the coach helps you decide.");
 Card(stack,"01  Get ready","Open Game Coach and Hades II. Game Coach starts the local model in the background; Hermes can stay closed. Settings shows Loading or Ready. In Settings, add your Platform API key, choose the game display, and balance voice volume. Opening the app alone does not activate the microphone or capture the game.");
 Card(stack,"02  Start coaching","Press Start coaching once. It starts local wake listening and the screen watcher together, then minimizes Game Coach. Keep Hades II in the foreground. The app never selects boons, moves your character, or presses game buttons.");
 Card(stack,"03  Talk naturally","Say “coach”, wait for the rising tone, then ask. Pause at the end of the question. You can say “thanks” to silence the reply, or “coach” while it is talking to interrupt and ask something new. Ctrl+Alt+L is the voice shortcut. Ask by voice does the same job from the app.");
 Card(stack,"Questions worth asking","“What is my build missing?”\r\n“Should I keep this boon or replace it?”\r\n“How do I use these effects together?”\r\n“What was the last boon I took?”\r\n“Explain the boss tips.”\r\n“I took [boon name].” — an explicit choice is recorded without a second confirmation.");
 Card(stack,"04  Read the cards","Boon screens compare the actual offers. A selected Sandbox build adds a separate target marker when a matching option is recognized. Keepsake advice considers your current needs. Boss cards appear during opening dialogue; ask the coach for more detail. Door markers require readable, confident reward choices, so they may be absent.");
 Card(stack,"05  Prepare a run","Current build shows your checkpoint, equipped weapon, Arcana and boons. Use Sandbox → Pick your build to choose an unlocked route. A plan guides choices; it does not equip anything. Capture starting setup is optional: show each equipment screen for at least four seconds, then say “coach, setup complete”. This review uses cloud analysis.");
 Card(stack,"Useful run check-ins","“Brief my run” prepares a local briefing.\r\n“What changed” compares against the last saved coaching checkpoint.\r\n“Debrief my run” reviews the last ended attempt.\r\n“Remember for next run [lesson]” keeps your own lesson across runs.\r\nFind these experiments under Sandbox → Run check-ins.");
 Card(stack,"06  Keep and share the story","Run history includes Completed clears and Failed attempts. Full build exports a single interactive HTML file: your friends can open it in a browser and hover, focus or tap boon icons. Summary PDF is the shorter recap. Share also offers a picture, text summary and an all-format bundle. Nothing is uploaded automatically.");
 Card(stack,"If something looks out of date","Keep the game in the foreground and give choice cards a few seconds. Current build → Refresh checkpoint reads the latest save; it cannot recover a pick the game has not saved. Tell the coach your choice if needed. For voice, wait for the tone and check the input meter. Settings → Local watcher → Model startup lets you locate the engine and model files. Connection details contains Save & test locally: it checks vision without capturing the game or spending Platform credits.");
 Card(stack,"What stays on your machine","Idle wake listening, automatic watching, save reading, run archives and local inference stay local. Activated questions use cloud transcription and coaching; spoken replies and run greetings use cloud speech. Activity shows measured requests and reported tokens. Pause coaching stops both the microphone and watcher without ending your game.");return page;}
 internal static Control About(Settings settings){return Tabs("About Game Coach","The Crossroads · a hybrid AI companion for Hades II",new[]{"Technical overview","Features"},new[]{Technical(settings),Features()});}
 static Control Technical(Settings settings){var page=Theme.Page();var stack=Layout(page,"The hybrid architecture","How this installed build combines local evidence and cloud conversation.");
 var creator=Theme.Section(Number(stack,"Creator & contact"));Theme.Row(creator,Theme.Heading("Created by "+AppCredits.Creator,16));Theme.Row(creator,Theme.Copy("Game Coach · The Crossroads"));var contact=new LinkLabel{Text="For inquiries: "+AppCredits.Email,AutoSize=true,LinkColor=Theme.Mint,VisitedLinkColor=Theme.Mint,ActiveLinkColor=Theme.Gold,LinkArea=new LinkArea(15,AppCredits.Email.Length),AccessibleName="Email "+AppCredits.Creator+": "+AppCredits.Email};Theme.Hint(contact,"Open your default email app with "+AppCredits.Email+" as the recipient. Nothing is sent automatically.");contact.LinkClicked+=(s,e)=>{try{System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo{FileName=AppCredits.MailTo,UseShellExecute=true});}catch{MessageBox.Show("Email "+AppCredits.Email+" using your preferred mail app.","Contact "+AppCredits.Creator);}};Theme.Row(creator,contact);Theme.Row(stack,creator);
 Card(stack,"A companion built around decisions","The app combines deterministic game evidence, local perception and on-demand cloud conversation. The local path watches for decision screens and offers concise advice. The voice coach connects individual choices to the player's intent and whole build. Game input is always the player's responsibility.");
 Card(stack,"The two paths","LOCAL: foreground Hades window → capture + Windows OCR → screen classification → validated decision context → app-managed local model when needed → overlay.\r\n\r\nVOICE: local wake grammar → ready tone → short question recording → cloud transcription → streamed cloud response → streamed speech. “Thanks” silences speech; a new wake request can interrupt the current answer.");
 Card(stack,"1 / Evidence before inference","Read-only parsing of the active Hades save recovers weapon, aspect, active Arcana, owned effects, levels, rarity and saved selection order. Installed English game text resolves names and current effect values. Unlocks and equipped effects remain distinct. The timestamp is a checkpoint, not a promise of live coverage. Explicit player reports can add later evidence; unselected visible options are never automatically owned.");
 Card(stack,"2 / A local watcher with lifecycle rules","Windows OCR detects structured screens and named boss dialogue. Repeated observations stabilize a choice screen. Local vision handles broader scene interpretation when needed. A semantic build key invalidates advice when decision-relevant equipment or intent changes; routine save-byte changes should not restart the comparison. Cancellation and foreground checks reject stale results. Two missing boss-dialogue reads dismiss the briefing. The app's cards are excluded from its own capture to reduce feedback loops.");
 Card(stack,"Local inference owned by the app","On launch, Game Coach starts a hidden llama.cpp server bound to loopback, then waits for the selected model to be ready. Its random local credential stays out of process arguments. A Windows job ties an app-owned engine to the app lifetime, including unexpected exits. Existing Hermes model files can be reused; Hermes itself is optional. A healthy running Hermes engine is shared and left alone on exit. External-server mode remains available. Local requests return constrained structured output, and the app checks names, effects and current evidence before displaying advice. Prepared boss tips use OCR and installed context. There is no automatic cloud fallback when the local model is unavailable.");
 Card(stack,"4 / On-demand cloud coaching","The selected cloud model handles typed or transcribed questions with the saved build, player reports and relevant screen context. Simple choice reports take a short acknowledgement path and skip web tools. Planning requests can use bounded web search for uncertain mechanics or current patch details. Public game terms are searched; private run narration is not used as a web query. Output streams so speech can begin before the whole answer is finished.");
 Card(stack,"Configured cloud services","Coach model: "+settings.Model+". Short questions use gpt-transcribe; spoken replies use "+CloudVoice.Model+" over Realtime. The local endpoint and model are visible in Settings → Local watcher → Connection details. This page describes installed behavior; service availability depends on your own connections.");
 Card(stack,"5 / Memory has several lifetimes","The active run combines checkpoint facts, player reports and inferred plans with their evidence labels. A separate journal retains selected build intent and user-written lessons. Ended runs have their own archive records, with final game-history statistics merged into richer captured checkpoints. A new run does not inherit the old run's gear. Historical data that the game compacted is marked missing rather than filled from today's equipment.");
 Card(stack,"6 / Results and reproducible exports","Two matching local OCR reads can capture a victory screen before final history is saved. Visible damage leaders remain separate from save-recorded totals. Synergy groups describe interactions and their conditions; they do not claim measured uptime or damage attribution. Full build HTML embeds the artwork and run details in one file. The summary PDF is generated locally with ReportLab. Bundles exclude API keys, raw saves, account settings and voice transcripts.");
 Card(stack,"7 / Measuring the hybrid system","Activity records provider, operation, model, elapsed request time, outcome and token counts when reported. Request duration includes queue and transfer time. It is not GPU utilization, and a request-count split is not a calculation of money saved. Missing token counts remain unknown. The latest 5,000 events are retained without their prompts, audio or images. Opening the graph makes no model request.");
 Card(stack,"8 / Latency and resource boundaries","Wake detection stays local. Automatic screen processing still consumes local CPU/GPU resources, even when it spends no Platform credits. Local model comparisons may take several seconds. Transcription, cloud reasoning and speech add network latency. Simple acknowledgements, cached cues, streaming speech and cancellation reduce perceived delay; the architecture is not a frame-by-frame combat reaction system.");
 Card(stack,"9 / Data and controls","Credentials use Windows user-bound encryption. Changing the display changes on-demand capture. Pause coaching stops wake listening and watching; Silence reply only stops the current speech. A separate watcher toggle is available in Settings for diagnostics or silent use. Exports and sharing remain local until the user sends a file. The app does not control the game or modify its save files.");
 Card(stack,"Limits to understand","English game layouts, readable foreground screens and fresh autosaves are required for reliable evidence. Some doors, UI animations and unusual menus may not be recognized. Older runs may lack levels, descriptions or choice timelines. Cloud and local recommendations can still be wrong; exact installed effects and player observations take precedence. Start/victory greetings vary recent wording and are deduplicated by run event.");
 var credits=Theme.Section(Number(stack,"Built with"));Theme.Row(credits,Theme.Copy("C# / .NET Framework + Windows Forms · WASAPI · System.Speech wake recognition · Windows OCR · llama.cpp local inference · OpenAI transcription, Responses and speech · Python / ReportLab PDF export.\r\n\r\nOriginal Game Coach crescent-and-crossroads mark and navigation icons. Hades II names and artwork belong to Supergiant Games. This is an independent companion, not an official Supergiant product."));
 var link=new LinkLabel{Text="Asset tooling: deppth2 / SGG Modding ↗",AutoSize=true,LinkColor=Theme.Mint};link.LinkClicked+=(s,e)=>System.Diagnostics.Process.Start("https://github.com/SGG-Modding/deppth");Theme.Row(credits,link);Theme.Row(stack,credits);return page;}

 static Control Tabs(string title,string subtitle,string[] names,Control[] pages){var root=new Panel{Dock=DockStyle.Fill,BackColor=Theme.Bg,Padding=new Padding(20)};var content=new Panel{Dock=DockStyle.Fill};var header=Theme.Stack();Theme.Row(header,Theme.Heading(title,25));Theme.Row(header,Theme.Copy(subtitle));var tabs=Theme.Flow();var buttons=new System.Collections.Generic.List<Button>();Action<int> select=index=>{for(int i=0;i<pages.Length;i++){pages[i].Visible=i==index;buttons[i].ForeColor=i==index?Theme.Mint:Theme.Muted;buttons[i].FlatAppearance.BorderColor=i==index?Theme.Mint:Theme.Line;}pages[index].BringToFront();Theme.Reflow(pages[index]);var scroll=pages[index] as ScrollableControl;if(scroll!=null){scroll.AutoScrollPosition=Point.Empty;if(scroll.IsHandleCreated)scroll.BeginInvoke(new Action(()=>{if(!scroll.IsDisposed)scroll.AutoScrollPosition=Point.Empty;}));}};for(int i=0;i<names.Length;i++){int index=i;pages[i].Dock=DockStyle.Fill;pages[i].Padding=new Padding(0,10,12,0);pages[i].Visible=false;content.Controls.Add(pages[i]);var button=Theme.Action(names[i],i==0?"book":"layers","Open "+names[i].ToLowerInvariant()+".",(s,e)=>select(index));buttons.Add(button);tabs.Controls.Add(button);}Theme.Row(header,tabs);root.Controls.Add(content);root.Controls.Add(header);Action reflow=()=>{if(!root.Visible)return;Theme.Reflow(header);header.PerformLayout();tabs.PerformLayout();header.AutoSize=false;header.Height=header.GetPreferredSize(new Size(header.Width,0)).Height;};root.VisibleChanged+=(s,e)=>reflow();root.SizeChanged+=(s,e)=>reflow();select(0);return root;}
 static void Links(TableLayoutPanel stack,params string[] links){var row=Theme.Flow();for(int i=0;i<links.Length;i+=2){string url=links[i+1];var link=new LinkLabel{Text=links[i]+" ↗",AutoSize=true,LinkColor=Theme.Mint,Margin=new Padding(0,0,20,10),AccessibleDescription=url};link.LinkClicked+=(s,e)=>System.Diagnostics.Process.Start(url);row.Controls.Add(link);}Theme.Row(stack,row);}
 static Control Install(){var page=Theme.Page();var stack=Layout(page,"Set up another PC","Manual setup guide · this is a portable app folder, not a universal installer.");
 Card(stack,"Prepare Windows and the game","Use Windows 11 with .NET Framework 4.8 or later, an English speech recognizer and English OCR language support. Allow desktop apps to use the microphone in Windows privacy settings. This app is compiled for x64; Windows ARM64 uses x64 emulation for the app and a native ARM64 model engine. Install Hades II, launch it once and use English game text. Keep the game in the foreground while coaching. Saves are read from your Windows user’s Saved Games / Hades II folder.");
 Card(stack,"Copy the app files","Place GameCoach.exe in a writable folder with assets, export_recap_pdf.py and the supporting app resources. Keep relative folders together. Use a clean distribution: do not share api-key.dpapi, local-runtime-key.dpapi, personal settings, run-memory.json, run-history or diagnostic/audio caches. Your friend creates their own key and local data. No Hermes bot, Node.js or Codex installation is required to run the prebuilt app.");
 Card(stack,"Install a compatible local engine","Install llama.cpp’s llama-server.exe with all its companion DLLs and licenses. Choose a build matching Windows ARM64 or x64 and your GPU backend, plus the corresponding GPU driver. Put it under runtime beside GameCoach.exe, or select its existing location in Settings → Local watcher → Model startup. The engine must support your model architecture, image input and structured JSON. The original development machine used ARM64 CUDA engine build 10964; another PC needs its own compatible build. GPU memory and speed must be validated locally.");
 Links(stack,"llama.cpp releases","https://github.com/ggml-org/llama.cpp/releases");
 Card(stack,"Add the vision model","This build uses Qwen3.6-35B-A3B-UD-Q4_K_M.gguf from the Unsloth Qwen3.6-35B-A3B-MTP-GGUF package, plus its matching mmproj-BF16.gguf vision projector. Weights and projector occupy about 24 GB on disk; inference needs additional memory for context and working buffers, and Hades needs headroom too. A large RAM figure alone does not guarantee GPU compatibility or gaming performance. Download both files, keep their matching versions, then choose both in Model startup. Enter Qwen3.6-35B-A3B-UD-Q4_K_M as the model ID. Compatible existing Hermes files can be detected; downloading through Hermes is optional. Leave automatic startup enabled, then Save & load model.");
 Links(stack,"Model and vision files","https://huggingface.co/unsloth/Qwen3.6-35B-A3B-MTP-GGUF");
 Card(stack,"Create your own OpenAI Platform key","Create a standard secret API key in your OpenAI Platform project. An organization Admin API key, ChatGPT login or Hermes runtime key is not the credential this app uses. Configure Platform billing/available API credit and model access for that project. Game Coach uses API-key billing; it does not implement ChatGPT subscription sign-in. If using restricted permissions, allow model requests for Responses, audio transcription and Realtime, plus the configured models and optional web-search tool. Read-only permission cannot run coaching requests.");
 Links(stack,"API setup guide","https://developers.openai.com/api/docs/quickstart","Key permissions","https://developers.openai.com/api/docs/guides/rbac","Platform keys","https://platform.openai.com/api-keys","API billing","https://platform.openai.com/settings/organization/billing/overview");
 Card(stack,"Connect the cloud coach","In Settings, paste your key into the masked API key box and select Save key. Keep it out of chats, screenshots and exports. The key is encrypted for the current Windows user; copying the encrypted file to another PC is not a setup method. The configured coach model must be available to that project; this build also calls gpt-transcribe and "+CloudVoice.Model+". Typed questions use Responses, voice questions add transcription, and replies use Realtime audio. Internet access to api.openai.com over HTTPS/WebSocket is required for these cloud features. Automatic local overlays do not use your Platform key.");
 Card(stack,"Enable PDF export (optional)","Install Python 3 and ReportLab for the summary PDF. In a terminal, run: python -m pip install reportlab. Create pdf-python.txt beside GameCoach.exe containing the full path to that Python executable, for example C:\\Python313\\python.exe. The app also recognizes runtime\\python\\python.exe. Keep export_recap_pdf.py beside the app. Full build HTML, PNG and text exports do not require Python; the all-format ZIP does because it includes the PDF.");
 Links(stack,"Python downloads","https://www.python.org/downloads/windows/","ReportLab","https://pypi.org/project/reportlab/");
 Card(stack,"Verify before playing","Wait for Local model: Ready. In Connection details, choose Save & test locally; it checks a synthetic image, the Epic comparison and offered-versus-owned handling without a cloud request. Select the correct microphone and game display. Press Start coaching; check the input meter, say “coach”, wait for the tone and ask a short question. That voice test uses your API credit. Test a foreground boon menu, then check Current build after a saved choice. Export a sample HTML and PDF. If local startup fails, verify architecture, GPU driver, model/projector and memory; there is no silent cloud fallback.");return page;}
 static Control Features(){var page=Theme.Page();var stack=Layout(page,"What Game Coach can do","Feature directory · automatic guidance, conversation, memory and shareable run stories.");
 Card(stack,"Launch and play","• Automatic local model startup, readiness status and cleanup on exit\r\n• One Start coaching button for voice listening and the watcher\r\n• Minimized play, a global voice shortcut, and Pause that preserves the run\r\n• Separate overlay-only mode, local vision test and manual connection controls");
 Card(stack,"Voice and conversation","• Local “coach” wake recognition and a ready tone\r\n• Cloud transcription, typed questions and streamed spoken answers\r\n• “Thanks” to silence a reply; a new wake request to interrupt and ask\r\n• Voice choice, volume and speaking-speed controls\r\n• Quick acknowledgements for explicit choices, without repeated confirmation\r\n• Optional web research for uncertain or complex planning questions\r\n• Varied encouragement and victory congratulations, with a settings toggle");
 Card(stack,"Automatic decision cards","• Boon comparisons using displayed rarity, effect, cost and your current build\r\n• Keepsake advice before runs and between regions\r\n• Boss tips during recognized opening dialogue; ask the coach to expand\r\n• Separate build-target markers on matching boon offers and confident door rewards\r\n• Foreground, evidence and cancellation checks to dismiss stale advice\r\n• Choice capture and buffered pickup verification; uncertain selections stay unconfirmed");
 Card(stack,"Persistent build knowledge","• Read-only save checkpoints for weapon, aspect, Arcana, boons, levels and rarity\r\n• Saved selection order and latest-boon recall\r\n• Player-reported choices and optional visual starting-setup review\r\n• Separate unlocked inventory, equipped loadout and unselected offers\r\n• Manual checkpoint refresh, selected build intent and lessons for future runs");
 Card(stack,"Sandbox and build planning","• Pick your build: curated routes filtered against recorded unlocks\r\n• Weapon, aspect, Arcana and boon targets with explanations\r\n• Guidance that adapts to your recorded choices\r\n• Run briefing, checkpoint comparison and post-run review\r\n• Personal priorities and practice reminders");
 Card(stack,"Run history and sharing","• Completed clears and Failed attempts, with retained incomplete historical data marked\r\n• Synergy groups with requirements and honest evidence limits\r\n• Loadout grouped as Boons → Equipment → Arcana, with category filters\r\n• Optional locally imported boon artwork and interactive level, rarity and effect details\r\n• Available time, Fear, rooms, damage and choice timeline statistics\r\n• Victory-screen context and visible damage leaders when captured\r\n• Standalone Full build HTML, Summary PDF, PNG card and text summary\r\n• Share bundle, clipboard sharing, local export folder and CSV statistics");
 Card(stack,"Hybrid activity and privacy","• Graphs of local and cloud requests, latency, outcomes and reported tokens\r\n• Local wake listening, OCR, inference and automatic screen watching\r\n• On-demand cloud reasoning, transcription and speech\r\n• Windows user-bound credential encryption and local archives\r\n• No automatic export upload, game input or save modification\r\n• Explicitly unknown data when a save, screenshot or older history lacks evidence");
 Card(stack,"Guides and settings","• How to use, installation instructions and this feature directory\r\n• Technical deep dive into evidence, inference, memory and exports\r\n• Explanatory mouseover tips, clear sections and accessible control labels\r\n• Microphone, display, voice, cloud model and local runtime settings");return page;}

}
}
