using System;using System.IO;using System.IO.Compression;using System.Linq;using System.Drawing;using System.Threading.Tasks;using System.Diagnostics;using System.Windows.Forms;using System.Collections.Specialized;
namespace GameCoach {
static class RecapExports {
 static string Q(string s){if(s.Contains("\"")||s.Contains("\r")||s.Contains("\n"))throw new IOException("Unsupported export path.");return "\""+s+"\"";}
 internal static string Summary(RunRecap r){var groups=RunArchive.Groups(r);return "Hades II · Night "+r.number+" · "+r.result+"\r\n"+r.weapon+" / "+r.aspect+"\r\n"+RecapPresentation.Time(r.victorySeconds??r.seconds)+" · "+RunArchive.Number(r.fear)+" Fear\r\n"+string.Join("\r\n",groups.Take(3).Select(g=>g.title+": "+string.Join(" + ",g.items.Select(i=>i.name))))+"\r\n"+AppCredits.ShareCredit;}
 internal static string PythonRuntime(){string configured=Path.Combine(Store.Root,"pdf-python.txt");if(File.Exists(configured)){string path=File.ReadAllText(configured).Trim();if(!File.Exists(path))throw new IOException("The Python path in pdf-python.txt was not found. See How to install.");return path;}string bundled=Path.Combine(Store.Root,"runtime","python","python.exe");if(File.Exists(bundled))return bundled;return "";}
 internal static async Task<string> Pdf(RunRecap r){
  string python=PythonRuntime();string script=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"export_recap_pdf.py");
  if(!File.Exists(python)||!File.Exists(script))throw new IOException("PDF export needs Python with ReportLab and export_recap_pdf.py. Set its path in pdf-python.txt beside the app; see How to install. HTML and PNG sharing are still available.");
  Directory.CreateDirectory(RunArchive.DirectoryPath);string path=Path.Combine(RunArchive.DirectoryPath,RunArchive.Stem(r)+".pdf"),temp=Path.Combine(RunArchive.DirectoryPath,"pdf-"+Guid.NewGuid().ToString("N")+".json"),output=path+".tmp-"+Guid.NewGuid().ToString("N");
  File.WriteAllText(temp,Store.Json.Serialize(new{run=r,time=RecapPresentation.Time(r.victorySeconds??r.seconds),image=RunArchive.ImagePath(r),groups=RunArchive.Groups(r).Select(g=>new{g.title,g.why,g.condition,g.items})}));
  try{using(var process=new Process{StartInfo=new ProcessStartInfo{FileName=python,Arguments=Q(script)+" "+Q(temp)+" "+Q(output),UseShellExecute=false,CreateNoWindow=true,WindowStyle=ProcessWindowStyle.Hidden,RedirectStandardError=true,RedirectStandardOutput=true}}){process.Start();var error=process.StandardError.ReadToEndAsync();var stdout=process.StandardOutput.ReadToEndAsync();if(!await Task.Run(()=>process.WaitForExit(45000))){process.Kill();throw new IOException("PDF export timed out. Try again; the saved recap remains available.");}string detail=await error;await stdout;if(process.ExitCode!=0)throw new IOException("PDF export failed: "+detail.Substring(0,Math.Min(450,detail.Length)));}
   using(var input=File.OpenRead(output)){var header=new byte[5];if(input.Read(header,0,5)!=5||System.Text.Encoding.ASCII.GetString(header)!="%PDF-")throw new IOException("PDF export did not produce a valid document.");}if(File.Exists(path))File.Replace(output,path,null);else File.Move(output,path);return path;
  }finally{if(File.Exists(temp))File.Delete(temp);if(File.Exists(output))File.Delete(output);}
 }
 internal static async Task<string> Bundle(RunRecap r){string pdf=await Pdf(r),png=RunArchive.ExportCard(r),html=Path.Combine(RunArchive.DirectoryPath,RunArchive.Stem(r)+".html");File.WriteAllText(html,RunArchive.Html(r));string path=Path.Combine(RunArchive.DirectoryPath,RunArchive.Stem(r)+"-share.zip"),temp=path+".tmp-"+Guid.NewGuid().ToString("N");try{using(var zip=ZipFile.Open(temp,ZipArchiveMode.Create)){foreach(string file in new[]{pdf,png,html})zip.CreateEntryFromFile(file,Path.GetFileName(file));var summary=zip.CreateEntry("Run-summary.txt");using(var writer=new StreamWriter(summary.Open()))writer.Write(Summary(r));}if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);return path;}finally{if(File.Exists(temp))File.Delete(temp);}}
 internal static void Share(IWin32Window owner,RunRecap r){using(var dialog=new Form{Text="Share Night "+r.number,Icon=AppGlyph.WindowIcon(),AutoScaleMode=AutoScaleMode.None,Size=new Size((int)(740*Theme.Scale),(int)(510*Theme.Scale)),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Bg,ForeColor=Theme.Text,Font=new Font("Segoe UI",11),MinimizeBox=false,MaximizeBox=false}){var scroll=new Panel{Dock=DockStyle.Fill,AutoScroll=true};dialog.Controls.Add(scroll);var content=Theme.Stack();content.Dock=DockStyle.Top;content.AutoSize=true;content.Padding=new Padding((int)(22*Theme.Scale));scroll.Controls.Add(content);Theme.Row(content,Theme.Heading("Share your night",24));Theme.Row(content,Theme.Copy("Send a quick snapshot, or bundle the interactive full build with its PDF summary."));var preview=Theme.ReadBox();preview.Text=Summary(r);preview.Height=(int)(180*Theme.Scale);Theme.Row(content,preview);var result=Theme.Copy("Files stay on this PC until you choose where to send them.");var actions=Theme.Flow();actions.Controls.Add(Theme.Action("Copy text","book","Copy a short result and synergy summary. Paste it into your preferred chat.",(s,e)=>{Clipboard.SetText(Summary(r));result.Text="Summary copied. Paste it into your preferred chat.";}));actions.Controls.Add(Theme.Action("Copy image","layers","Copy the share card to the clipboard. Paste into a chat or image editor.",(s,e)=>{using(var image=new Bitmap(RunArchive.ExportCard(r)))Clipboard.SetImage(image);result.Text="Share card copied. Paste it into a chat that accepts images.";}));var bundle=Theme.Action("Create share bundle","share","Save a ZIP with the interactive HTML, summary PDF, PNG and text summary. Copies the ZIP as a file for pasting.",null);bundle.Click+=async(s,e)=>{bundle.Enabled=false;result.Text="Creating summary PDF, full build HTML and share card…";try{var path=await Bundle(r);if(dialog.IsDisposed)return;Clipboard.SetFileDropList(new StringCollection{path});result.Text="Bundle copied as a file. Paste it into a chat, or use Open exports.";}catch(Exception ex){if(!dialog.IsDisposed)result.Text=ex.Message;}finally{if(!dialog.IsDisposed)bundle.Enabled=true;}};actions.Controls.Add(bundle);actions.Controls.Add(Theme.Action("Open exports","download","Open the local run-history folder containing your exported files.",(s,e)=>{Directory.CreateDirectory(RunArchive.DirectoryPath);Process.Start(new ProcessStartInfo{FileName=RunArchive.DirectoryPath,UseShellExecute=true});}));Theme.Row(content,actions);Theme.Row(content,result);dialog.Size=new Size(Math.Min(dialog.Width,Screen.FromControl(dialog).WorkingArea.Width-40),Math.Min(dialog.Height,Screen.FromControl(dialog).WorkingArea.Height-50));dialog.ShowDialog(owner);}}
}
}
