using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using System.Windows.Forms;
namespace GameCoach {
public class RecapItem {public string id,name,category,rarity,description,evidence;public double? level;public int? rank;public string[] effects=new string[0];}
public class DamageRow {public string name;public double amount;}
public class RunRecap {
 public int version=1,number;public string profile,result,route,endingRoom,killedBy,weapon,aspect,importedAt,checkpointAt;public bool cleared;
 public double? seconds,totalSeconds,damageTaken,damageDealt,fear,rooms,grasp,aspectRank;
 public RecapItem[] items=new RecapItem[0];public string[] keepsakes=new string[0];public SavedChoice[] choices=new SavedChoice[0];
 public int presentationVersion;public string resultEvidence,victoryImage,victoryAt;public double? victorySeconds;public DamageRow[] inflicted=new DamageRow[0],suffered=new DamageRow[0];public string damageEvidence;
 public override string ToString(){return "Night "+number+"  ·  "+result+"\r\n"+weapon+"  ·  "+RunArchive.Duration(seconds);}
}
class SynergyGroup {internal string title,why,condition;internal RecapItem[] items;}
static class HistoryProjection {
 static Dictionary<string,string> arcana;
 internal static string Category(string id,TraitNames names){if(arcana==null){arcana=new Dictionary<string,string>();foreach(var d in UnlockReader.Definitions(Path.Combine(names.ScriptDirectory,"MetaUpgradeData.lua"))){string trait=UnlockReader.Field(d.Value,"TraitName");if(trait.Length>0)arcana[trait]=d.Key;}}if(arcana.ContainsKey(id))return "Arcana";if(UnlockReader.Aspects.Any(f=>f.Skip(1).Contains(id)))return "Aspect";if(id.EndsWith("Keepsake"))return "Keepsake";if(id.EndsWith("WeaponBoon"))return "Attack";if(id.EndsWith("SpecialBoon"))return "Special";if(id.EndsWith("CastBoon")||id=="CastAnywhereBoon")return "Cast";if(id.EndsWith("ManaBoon"))return "Magick";if(id.EndsWith("SprintBoon"))return "Rush";return "Support";}
 static string ItemName(string id,TraitNames names){string key;return arcana!=null&&arcana.TryGetValue(id,out key)?names.Name(key):names.Name(id);}
 static double? Number(object r,string key){var v=HadesSave.Get(r,key);return v is double?(double?)((double)v):null;}
 internal static RunRecap[] Read(object state,string profile,TraitNames names){return HadesSave.Ordered(HadesSave.Get(state,"RunHistory")).Select(entry=>Project(entry.Value,(int)(double)entry.Key,profile,names)).ToArray();}
 internal static RunRecap Project(object raw,int number,string profile,TraitNames names){
  int code=(int)HadesSave.Number(HadesSave.Get(raw,"RunResult"));bool clear=new[]{1,3,5,7,8,9}.Contains(code);var ids=HadesSave.Table(HadesSave.Get(raw,"TraitCache")).Where(k=>HadesSave.Number(k.Value)>0).Select(k=>HadesSave.Str(k.Key)).ToArray();
  var items=ids.Select(id=>{string category=Category(id,names);return new RecapItem{id=id,category=category,name=ItemName(id,names),rarity=HadesSave.Str(HadesSave.Get(HadesSave.Get(raw,"TraitRarityCache"),id))};}).Where(i=>i.name!=i.id&&!i.id.StartsWith("Dummy")&&i.id!="VanillaState").ToArray();
  var weapon=UnlockReader.Aspects.FirstOrDefault(f=>object.Equals(HadesSave.Get(HadesSave.Get(raw,"WeaponsCache"),f[0]),true));string ending=HadesSave.Str(HadesSave.Get(raw,"EndingRoomName"));var damage=HadesSave.Table(HadesSave.Get(raw,"DamageDealtByHeroRecord"));var rooms=HadesSave.Table(HadesSave.Get(raw,"RoomsEntered"));
  return new RunRecap{number=number,profile=profile,cleared=clear,result=clear?"Completed":new[]{2,4,6,10}.Contains(code)?"Failed":"Outcome unknown",route=code==5||code==6?"Trial":code==9||code==10?"Dream":new[]{3,4,8}.Contains(code)?"Surface":"Underworld",endingRoom=ending,killedBy=HadesSave.Str(HadesSave.Get(raw,"KilledByName")),weapon=weapon==null?"Weapon unrecorded":names.Name(weapon[0]),aspect=items.Where(i=>i.category=="Aspect").Select(i=>i.name).FirstOrDefault()??"Aspect unrecorded",seconds=Number(raw,"GameplayTime"),totalSeconds=Number(raw,"TotalTime"),damageTaken=Number(raw,"TotalDamageTaken"),damageDealt=damage.Count==0?null:(double?)damage.Values.Sum(v=>HadesSave.Number(v)),fear=Number(raw,"ShrinePointsCache"),grasp=Number(raw,"MetaUpgradeCostCache"),rooms=rooms.Count==0?null:(double?)rooms.Values.Sum(v=>HadesSave.Number(v)),items=items,keepsakes=HadesSave.Ordered(HadesSave.Get(raw,"KeepsakeCache")).Select(k=>names.Name(HadesSave.Str(k.Value))).ToArray()};
 }
}
static class RunArchive {
 internal static string DirectoryPath{get{return Path.Combine(Store.Root,"run-history");}}
 static string Safe(string value){return Regex.Replace(value??"unknown",@"[^a-zA-Z0-9_-]","_");}
 internal static string Stem(RunRecap r){return Safe(r.profile)+"-night-"+r.number.ToString("0000");}
 internal static string ImagePath(RunRecap r){return !string.IsNullOrEmpty(r.victoryImage)&&r.victoryImage==Stem(r)+"-victory.jpg"?Path.Combine(DirectoryPath,r.victoryImage):"";}
 internal static RunRecap CaptureVictory(SavedBuild build,VictoryRead screen,byte[] image){
  var r=RecapDetails.FromVictory(build,screen);if(r==null)return null;string file=Path.Combine(DirectoryPath,Stem(r)+".json");var old=Read<RunRecap>(file);
  if(old!=null&&!string.IsNullOrEmpty(old.victoryAt))return old;
  Merge(r,old);if(old!=null&&old.cleared){r.items=old.items;r.keepsakes=old.keepsakes;r.seconds=old.seconds??r.seconds;RecapDetails.Enrich(r,build);r.resultEvidence=old.resultEvidence??"Game-save history";}r.presentationVersion=5;r.importedAt=old==null?DateTime.UtcNow.ToString("o"):old.importedAt;r.victoryImage=Stem(r)+"-victory.jpg";Directory.CreateDirectory(DirectoryPath);
  using(var ms=new MemoryStream(image))using(var bitmap=new Bitmap(ms))bitmap.Save(ImagePath(r),ImageFormat.Jpeg);
  Atomic(file,Store.Json.Serialize(r));Atomic(Path.Combine(DirectoryPath,Stem(r)+".html"),Html(r));Diagnostics.Log("Victory captured: "+Stem(r)+" · "+Duration(r.seconds)+" · final history pending.");return r;
 }
 static string SnapshotPath(string profile,int number){return Path.Combine(Store.Root,"run-snapshots",Safe(profile)+"-"+number+".json");}
 static void Atomic(string path,string text){Directory.CreateDirectory(Path.GetDirectoryName(path));string tmp=path+".tmp";File.WriteAllText(tmp,text,Encoding.UTF8);if(File.Exists(path))File.Replace(tmp,path,null);else File.Move(tmp,path);}
 static T Read<T>(string path) where T:class{try{return new FileInfo(path).Length>4*1024*1024?null:Store.Json.Deserialize<T>(File.ReadAllText(path));}catch{return null;}}
 internal static RunRecap[] All(){if(!Directory.Exists(DirectoryPath))return new RunRecap[0];return Directory.GetFiles(DirectoryPath,"*-night-*.json").Select(Read<RunRecap>).Where(r=>r!=null&&r.version==1).OrderByDescending(r=>r.number).ThenBy(r=>r.profile).ToArray();}
 static readonly HashSet<string> migrated=new HashSet<string>();
 static void BackfillCheckpoints(){if(!migrated.Add(Store.Root))return;string folder=Path.Combine(Store.Root,"run-archive");if(!Directory.Exists(folder))return;foreach(string file in Directory.GetFiles(folder,"*.json").Take(1000)){var record=Read<RunRecord>(file);var b=record==null?null:record.gameState;if(b==null||(b.choices??new SavedChoice[0]).Length==0||!Regex.IsMatch(b.map??"",@"^[FGHINOPQ]_"))continue;string path=SnapshotPath(b.profile,b.completedRuns+1);var old=Read<SavedBuild>(path);DateTime a,z;if(old==null||(DateTime.TryParse(b.savedAt,out a)&&DateTime.TryParse(old.savedAt,out z)&&a>z))Atomic(path,Store.Json.Serialize(b));}}
 internal static void Sync(SavedBuild b){
  if(b==null)return;Directory.CreateDirectory(DirectoryPath);BackfillCheckpoints();
  foreach(var original in b.completedHistory??new RunRecap[0]){var r=Store.Json.Deserialize<RunRecap>(Store.Json.Serialize(original));string file=Path.Combine(DirectoryPath,Stem(r)+".json");var prior=Read<RunRecap>(file);Merge(r,prior);var checkpoint=Read<SavedBuild>(SnapshotPath(r.profile,r.number));if(checkpoint!=null&&checkpoint.profile==r.profile&&checkpoint.completedRuns+1==r.number){RecapDetails.Enrich(r,checkpoint);}
   r.presentationVersion=5;r.resultEvidence="Game-save history";r.importedAt=prior==null?DateTime.UtcNow.ToString("o"):prior.importedAt;string json=Store.Json.Serialize(r);if(prior!=null&&Store.Json.Serialize(prior)==json)continue;Atomic(file,json);Atomic(Path.Combine(DirectoryPath,Stem(r)+".html"),Html(r));Diagnostics.Log("Run recap saved: "+Stem(r)+" · "+r.result+" · "+r.items.Length+" recorded effects.");
  }
  // The header is completed-runs count. The active run will become history
  // entry count+1. Keep the latest checkpoint without asserting it is final.
  if((b.choices??new SavedChoice[0]).Length>0&&Regex.IsMatch(b.map??"",@"^[FGHINOPQ]_"))Atomic(SnapshotPath(b.profile,b.completedRuns+1),Store.Json.Serialize(b));
 }
 internal static void Merge(RunRecap r,RunRecap old){if(old==null)return;r.seconds=r.seconds??old.seconds;r.totalSeconds=r.totalSeconds??old.totalSeconds;r.damageTaken=r.damageTaken??old.damageTaken;r.damageDealt=r.damageDealt??old.damageDealt;r.rooms=r.rooms??old.rooms;r.fear=r.fear??old.fear;r.grasp=r.grasp??old.grasp;r.aspectRank=old.aspectRank;r.choices=old.choices??new SavedChoice[0];r.checkpointAt=old.checkpointAt;r.victoryImage=old.victoryImage;r.victoryAt=r.victoryAt??old.victoryAt;r.victorySeconds=r.victorySeconds??old.victorySeconds;if(r.inflicted.Length==0)r.inflicted=old.inflicted??new DamageRow[0];if(r.suffered.Length==0)r.suffered=old.suffered??new DamageRow[0];r.damageEvidence=r.damageEvidence??old.damageEvidence;foreach(var item in r.items){var previous=old.items.FirstOrDefault(i=>i.id==item.id);if(previous!=null){if(string.IsNullOrEmpty(item.rarity))item.rarity=previous.rarity;item.description=previous.description;item.effects=previous.effects;item.level=previous.level;item.rank=previous.rank;item.evidence=previous.evidence;}}if(r.items.Length==0)r.items=old.items;if(r.keepsakes.Length==0)r.keepsakes=old.keepsakes;}
 internal static SynergyGroup[] Groups(RunRecap r){return RecapDetails.Groups(r);}
 internal static string Duration(double? seconds){if(!seconds.HasValue||seconds<0)return "Not recorded";var t=TimeSpan.FromSeconds(seconds.Value);return ((int)t.TotalMinutes).ToString("00")+":"+t.Seconds.ToString("00");}
 internal static string Number(double? n){return n.HasValue?n.Value.ToString("N0",CultureInfo.InvariantCulture):"Not recorded";}
 static string H(string text){return WebUtility.HtmlEncode(text??"");}
 internal static string Html(RunRecap r){return RecapPresentation.Html(r);}
 internal static string ExportCard(RunRecap r){return RecapPresentation.ExportCard(r);}
 internal static string ExportStats(){Directory.CreateDirectory(DirectoryPath);string path=Path.Combine(DirectoryPath,"run-statistics.csv");Func<string,string> q=v=>{v=v??"";if(v.Length>0&&"=+-@\t\r\n".IndexOf(v[0])>=0)v="'"+v;return "\""+v.Replace("\"","\"\"")+"\"";};var b=new StringBuilder("Profile,Run,Result,Route,Weapon,Aspect,GameplaySeconds,Fear,RoomVisits,DamageTaken,DamageDealt\r\n");foreach(var r in All())b.AppendLine(string.Join(",",new[]{r.profile,r.number.ToString(),r.result,r.route,r.weapon,r.aspect,r.seconds.HasValue?r.seconds.Value.ToString(CultureInfo.InvariantCulture):"",r.fear.HasValue?r.fear.Value.ToString(CultureInfo.InvariantCulture):"",r.rooms.HasValue?r.rooms.Value.ToString(CultureInfo.InvariantCulture):"",r.damageTaken.HasValue?r.damageTaken.Value.ToString(CultureInfo.InvariantCulture):"",r.damageDealt.HasValue?r.damageDealt.Value.ToString(CultureInfo.InvariantCulture):""}.Select(q)));Atomic(path,b.ToString());return path;}
}
class RunArchivePanel : UserControl {
 bool refreshing;FlowLayoutPanel sectionTabs;readonly ListBox runs;readonly ComboBox filter;readonly Label summary;readonly Panel preview;readonly TableLayoutPanel recap;string stamp="",view="Synergies",loadoutFilter="All";
 internal RunArchivePanel(){Dock=DockStyle.Fill;BackColor=Theme.Bg;ForeColor=Theme.Text;Padding=new Padding(20);var layout=Theme.Stack();layout.Dock=DockStyle.Fill;layout.AutoSize=false;Controls.Add(layout);Theme.ScrollLayout(this,layout,550);Theme.Row(layout,Theme.Heading("Run history",24));summary=Theme.Copy("Every night leaves a story. Completed runs appear here automatically.");Theme.Row(layout,summary);var actions=Theme.Flow();filter=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=(int)(150*Theme.Scale),AccessibleName="Run outcome filter"};filter.Items.AddRange(new[]{"All nights","Completed","Failed"});filter.SelectedIndex=0;Theme.Hint(filter,"Filter the archive by run outcome. Failed attempts remain available alongside completed clears.");actions.Controls.Add(filter);actions.Controls.Add(Theme.Action("Refresh","refresh","Import the latest completed and failed attempts from the local game save.",(s,e)=>{SaveMemorySync.Refresh(true);RefreshRuns(true);}));actions.Controls.Add(Theme.Action("Full build · HTML","download","Save the interactive build with embedded boon icons, hover details, synergies and results. One file your friends can open in a browser.",(s,e)=>ExportFullBuild()));actions.Controls.Add(Theme.Action("Summary · PDF","download","Save a short, print-friendly run summary. Use Full build for every boon and its hover details.",async(s,e)=>await ExportPdf()));actions.Controls.Add(Theme.Action("Share","share","Copy a summary or image, or bundle the full HTML build and summary PDF together.",(s,e)=>{var selected=runs.SelectedItem as RunRecap;if(selected!=null)RecapExports.Share(this,selected);}));actions.Controls.Add(Theme.Action("Stats · CSV","chart","Export recorded statistics for all archived runs as a spreadsheet-readable CSV.",(s,e)=>{try{var path=RunArchive.ExportStats();summary.Text="Saved all-run statistics to "+path;}catch(Exception ex){summary.Text=ex.Message;}}));Theme.Row(layout,actions);
  var split=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1};split.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,27));split.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,73));split.RowStyles.Add(new RowStyle(SizeType.Percent,100));int row=layout.RowCount++;layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.Controls.Add(split,0,row);
  runs=new ListBox{Dock=DockStyle.Fill,BackColor=Theme.Card,ForeColor=Theme.Text,BorderStyle=BorderStyle.None,IntegralHeight=false,DrawMode=DrawMode.OwnerDrawFixed,ItemHeight=(int)(90*Theme.Scale),AccessibleName="Completed nights",Margin=new Padding(0,0,12,0)};runs.DrawItem+=Draw;split.Controls.Add(runs,0,0);var right=Theme.Stack();right.Dock=DockStyle.Fill;right.AutoSize=false;split.Controls.Add(right,1,0);var pages=Theme.Flow();sectionTabs=pages;foreach(string label in new[]{"Synergies","Results","Loadout","Choice timeline"}){string page=label;var tab=Theme.Button(label,(s,e)=>{view=page;ShowRun();});Theme.Hint(tab,"Show this run's "+label.ToLowerInvariant()+". Missing historical values remain unknown.");pages.Controls.Add(tab);}Theme.Row(right,pages);preview=new Panel{Dock=DockStyle.Fill,AutoScroll=true,BackColor=Theme.Bg,AccessibleName="Run recap preview"};recap=Theme.Stack();recap.Padding=new Padding(0,0,10,10);preview.Controls.Add(recap);int detailRow=right.RowCount++;right.RowStyles.Add(new RowStyle(SizeType.Percent,100));right.Controls.Add(preview,0,detailRow);runs.SelectedIndexChanged+=(s,e)=>{if(!refreshing)ShowRun();};filter.SelectedIndexChanged+=(s,e)=>RefreshRuns(true);VisibleChanged+=(s,e)=>{if(Visible){SaveMemorySync.Refresh();RefreshRuns();if(runs.SelectedIndex>=0)runs.TopIndex=runs.SelectedIndex;}};Theme.StyleInputs(this);RefreshRuns(true);
 }
 void Draw(object sender,DrawItemEventArgs e){if(e.Index<0)return;var r=(RunRecap)runs.Items[e.Index];bool selected=(e.State&DrawItemState.Selected)!=0;using(var bg=new SolidBrush(selected?Color.FromArgb(31,61,54):Theme.Card))e.Graphics.FillRectangle(bg,e.Bounds);int p=(int)(10*Theme.Scale);using(var title=new Font("Segoe UI Semibold",11))using(var small=new Font("Segoe UI",9)){TextRenderer.DrawText(e.Graphics,"Night "+r.number+" · "+r.result,title,new Rectangle(e.Bounds.X+p,e.Bounds.Y+p,e.Bounds.Width-p*2,(int)(24*Theme.Scale)),r.cleared?Theme.Mint:Theme.Gold,TextFormatFlags.NoPadding|TextFormatFlags.EndEllipsis);TextRenderer.DrawText(e.Graphics,r.weapon+"\r\n"+RunArchive.Duration(r.seconds)+" · "+r.route,small,new Rectangle(e.Bounds.X+p,e.Bounds.Y+p+(int)(27*Theme.Scale),e.Bounds.Width-p*2,(int)(43*Theme.Scale)),Theme.Muted,TextFormatFlags.NoPadding|TextFormatFlags.WordBreak|TextFormatFlags.EndEllipsis);}e.DrawFocusRectangle();}
 internal void RefreshRuns(bool force=false){var all=RunArchive.All();string next=string.Join("|",all.Select(r=>r.profile+":"+r.number+":"+r.items.Length+":"+r.choices.Length+":"+r.presentationVersion+":"+r.resultEvidence+":"+r.victoryAt));if(!force&&next==stamp)return;stamp=next;var selected=runs.SelectedItem as RunRecap;string key=selected==null?"":RunArchive.Stem(selected);refreshing=true;runs.BeginUpdate();runs.Items.Clear();runs.Items.AddRange(all.Where(r=>filter.SelectedIndex==0||r.result==filter.Text).ToArray());var retain=runs.Items.Cast<RunRecap>().FirstOrDefault(r=>RunArchive.Stem(r)==key)??runs.Items.Cast<RunRecap>().FirstOrDefault();if(retain!=null)runs.SelectedItem=retain;runs.EndUpdate();refreshing=false;if(runs.SelectedIndex>=0)runs.TopIndex=runs.SelectedIndex;summary.Text=all.Length+" nights archived · "+all.Count(r=>r.cleared)+" clears · select a night to explore or share.";ShowRun();}
 TableLayoutPanel Card(string eyebrow,string title,string text,Color color){var card=Theme.Stack();card.BackColor=Theme.Card;card.Padding=new Padding((int)(16*Theme.Scale));card.Paint+=(s,e)=>{using(var pen=new Pen(Theme.Line))e.Graphics.DrawRectangle(pen,0,0,card.Width-1,card.Height-1);};if(eyebrow.Length>0){var label=Theme.Copy(eyebrow);label.ForeColor=color;label.Font=new Font("Segoe UI Semibold",9);Theme.Row(card,label);}if(title.Length>0)Theme.Row(card,Theme.Heading(title,18));if(text.Length>0)Theme.Row(card,Theme.Copy(text));Theme.Row(recap,card);return card;}
 void ShowRun(){if(recap==null)return;if(sectionTabs!=null)foreach(Button tab in sectionTabs.Controls){tab.ForeColor=tab.Text==view?Theme.Mint:Theme.Muted;tab.FlatAppearance.BorderColor=tab.Text==view?Theme.Mint:Theme.Line;}recap.SuspendLayout();while(recap.Controls.Count>0){var c=recap.Controls[0];recap.Controls.Remove(c);c.Dispose();}recap.RowStyles.Clear();recap.RowCount=0;var r=runs.SelectedItem as RunRecap;
  if(r==null)Card("YOUR NEXT CHAPTER","No matching nights","Open Hades II and refresh history to import past attempts.",Theme.Gold);
  else{Card(r.result.ToUpperInvariant()+"  /  "+r.route.ToUpperInvariant(),"Night "+r.number,r.weapon+" · "+r.aspect, r.cleared?Theme.Mint:Theme.Gold);
   if(view=="Synergies"){
    Card("THE NUMBERS",RunArchive.Duration(r.seconds)+" gameplay time",RunArchive.Number(r.fear)+" Fear   ·   "+RunArchive.Number(r.rooms)+" room visits\r\nDamage taken: "+RunArchive.Number(r.damageTaken)+"   ·   Dealt: "+RunArchive.Number(r.damageDealt),Theme.Mint);
    if(!string.IsNullOrEmpty(r.killedBy))Card("WHERE THE NIGHT ENDED",r.killedBy,"Ending room: "+r.endingRoom,Theme.Gold);
    var groups=RunArchive.Groups(r);if(groups.Length==0)Card("BUILD SIGNATURE","A flexible toolkit","No supported synergy group is confirmed by the retained data. See Loadout for the recorded effects.",Theme.Mint);foreach(var group in groups){var section=Card("BUILD SIGNATURE",group.title,group.why+"\r\n\r\n"+group.condition,Theme.Mint);Theme.Row(section,BoonArt.Grid(group.items));}
    Card("KEEP THE STORY","Your night, ready to share","Full build saves an interactive HTML file. Summary saves a shorter PDF. Share offers an image, text and an all-format bundle.",Theme.Gold);
   }else if(view=="Results"){
    Card("RUN RESULTS",RecapPresentation.Time(r.victorySeconds??r.seconds),"Fear: "+RunArchive.Number(r.fear)+"\r\n"+(r.resultEvidence??"Game-save history"),Theme.Mint);
    Card("MOST DAMAGE INFLICTED","",r.inflicted.Length==0?"Not retained":string.Join("\r\n",r.inflicted.Select(x=>x.name+"  ·  "+RunArchive.Number(x.amount))),Theme.Mint);
    Card("MOST DAMAGE SUFFERED","",r.suffered.Length==0?"Not retained":string.Join("\r\n",r.suffered.Select(x=>x.name+"  ·  "+RunArchive.Number(x.amount))),Theme.Gold);
    Card("EVIDENCE","",(r.damageEvidence??"No source breakdown retained")+". Listed leaders are not a total or a measurement of each synergy.",Theme.Muted);string screenshot=RunArchive.ImagePath(r);if(File.Exists(screenshot)){var pic=new PictureBox{Height=(int)(300*Theme.Scale),SizeMode=PictureBoxSizeMode.Zoom,BackColor=Theme.Card,AccessibleName="Victory screen"};using(var source=Image.FromFile(screenshot))pic.Image=new Bitmap(source);pic.Disposed+=(s,e)=>pic.Image.Dispose();Theme.Row(recap,pic);}
   }else if(view=="Loadout"){
    var filters=Theme.Flow();foreach(string name in new[]{"All","Boons","Equipment","Arcana"}){string category=name;var button=Theme.Button(name,(s,e)=>{loadoutFilter=category;ShowRun();});button.ForeColor=name==loadoutFilter?Theme.Mint:Theme.Muted;button.FlatAppearance.BorderColor=name==loadoutFilter?Theme.Mint:Theme.Line;Theme.Hint(button,name=="All"?"Show Boons, Equipment and Arcana as separate sections, in that order.":"Show only "+name.ToLowerInvariant()+" and hide the other loadout sections.");filters.Controls.Add(button);}Theme.Row(recap,filters);
    foreach(string name in BuildSections.Names){if(loadoutFilter!="All"&&loadoutFilter!=name)continue;var items=r.items.Where(i=>BuildSections.Category(i)==name).ToArray();var section=Card("RECORDED LOADOUT",name,"Hover an icon for its level and effect. Click to keep the details open.",Theme.Mint);if(items.Length>0)Theme.Row(section,BoonArt.Grid(items));else Theme.Row(section,Theme.Copy("No items were retained in this section."));if(name=="Equipment")Theme.Row(section,Theme.Copy("Keepsakes used: "+(r.keepsakes.Length==0?"Not retained":string.Join(" → ",r.keepsakes))));if(name=="Arcana")Theme.Row(section,Theme.Copy("Recorded Grasp: "+RunArchive.Number(r.grasp)+". Historical ranks and effects can be missing."));}
   }else if(r.choices.Length==0)Card("CHOICE TIMELINE","Not retained for this night","The game has already compacted this run's choice history. New runs retain the latest checkpoint while Game Coach is open.",Theme.Gold);
   else{Card("CHECKPOINT COVERAGE","Choices along the route","Sequence through the last captured checkpoint; later unsaved choices may be missing. Rarity is shown at pickup.",Theme.Gold);foreach(var c in r.choices)Card("CHOICE "+c.order+"  /  DEPTH "+c.depth,c.name,c.rarityAtChoice+" · "+(c.kind??"").Replace('_',' ')+(string.IsNullOrEmpty(c.replaced)?"":" · replaced "+BuildPlanner.Names.Name(c.replaced)),Theme.Mint);}
  }recap.ResumeLayout(true);preview.AutoScrollPosition=Point.Empty;Theme.Reflow(recap);
 }

 void ExportFullBuild(){var r=runs.SelectedItem as RunRecap;if(r==null)return;try{string path=Path.Combine(RunArchive.DirectoryPath,RunArchive.Stem(r)+".html");File.WriteAllText(path,RunArchive.Html(r));using(var dialog=new SaveFileDialog{FileName=Path.GetFileName(path),InitialDirectory=RunArchive.DirectoryPath,Filter="Interactive full build|*.html",Title="Export full build"}){if(dialog.ShowDialog(this)==DialogResult.OK&&!string.Equals(Path.GetFullPath(dialog.FileName),Path.GetFullPath(path),StringComparison.OrdinalIgnoreCase))File.Copy(path,dialog.FileName,true);}summary.Text="Full build saved. Open the HTML file in a browser; all artwork is embedded.";}catch(Exception ex){summary.Text=ex.Message;}}
 async System.Threading.Tasks.Task ExportPdf(){var r=runs.SelectedItem as RunRecap;if(r==null)return;summary.Text="Creating your PDF…";try{string path=await RecapExports.Pdf(r);using(var dialog=new SaveFileDialog{FileName=Path.GetFileName(path),InitialDirectory=RunArchive.DirectoryPath,Filter="PDF recap|*.pdf",Title="Save run recap PDF"}){if(dialog.ShowDialog(this)!=DialogResult.OK){summary.Text="PDF saved in the local run-history folder.";return;}if(!string.Equals(Path.GetFullPath(dialog.FileName),Path.GetFullPath(path),StringComparison.OrdinalIgnoreCase))File.Copy(path,dialog.FileName,true);summary.Text="PDF saved: "+dialog.FileName;}}catch(Exception ex){summary.Text=ex.Message;}}
 void Export(bool card){var r=runs.SelectedItem as RunRecap;if(r==null)return;try{string path=card?RunArchive.ExportCard(r):Path.Combine(RunArchive.DirectoryPath,RunArchive.Stem(r)+".html");if(card){using(var dialog=new SaveFileDialog{FileName=Path.GetFileName(path),InitialDirectory=RunArchive.DirectoryPath,Filter="PNG share card|*.png",Title="Save a shareable night card"}){if(dialog.ShowDialog(this)!=DialogResult.OK)return;if(!string.Equals(Path.GetFullPath(dialog.FileName),Path.GetFullPath(path),StringComparison.OrdinalIgnoreCase))File.Copy(path,dialog.FileName,true);summary.Text="Share card saved: "+dialog.FileName;}}else System.Diagnostics.Process.Start(path);}catch(Exception ex){summary.Text="Export could not finish: "+ex.Message;}}
}
}
