using System;using System.IO;using System.Linq;using System.Text;using System.Text.RegularExpressions;using System.Collections.Generic;using System.Drawing;using System.Drawing.Imaging;using System.Drawing.Drawing2D;using System.Globalization;using System.Net;
namespace GameCoach {
class VictoryRead {
 internal double seconds;internal double? fear;internal DamageRow[] inflicted,suffered;
 internal string Key{get{return seconds.ToString("F2",CultureInfo.InvariantCulture)+"|"+string.Join("|",inflicted.Concat(suffered).Select(d=>d.name+":"+d.amount));}}
 internal static bool Header(ScreenLine[] lines){return lines!=null&&lines.Any(l=>l.Y<.2&&l.X>.28&&l.X<.7&&Regex.IsMatch(ScreenSignals.Clean(l.Text).Replace(" ",""),@"^victory[il1]?$"))&&lines.Any(l=>l.X>.75&&l.Y>.17&&l.Y<.4&&ScreenSignals.Clean(l.Text)=="results");}
 static string Text(string s){return Regex.Replace(s??"",@"\s+"," ").Trim();}
 internal static VictoryRead Parse(ScreenLine[] lines){
  if(!Header(lines))return null;var time=lines.FirstOrDefault(l=>l.X>.91&&l.Y>.24&&l.Y<.36&&Regex.IsMatch(Text(l.Text),@"^\d[\d :]*[.]\d{2}$"));
  if(time==null||!lines.Any(l=>l.X>.75&&Math.Abs(l.Y-time.Y)<.025&&ScreenSignals.Clean(l.Text).Contains("clear time")))return null;
  string digits=Regex.Replace(time.Text,@"[^0-9.]","");var match=Regex.Match(digits,@"^(\d{1,4})(\d{2}[.]\d{2})$");double minutes,seconds;
  if(!match.Success||!double.TryParse(match.Groups[1].Value,NumberStyles.None,CultureInfo.InvariantCulture,out minutes)||!double.TryParse(match.Groups[2].Value,NumberStyles.AllowDecimalPoint,CultureInfo.InvariantCulture,out seconds)||seconds>=60)return null;
  var inflicted=lines.FirstOrDefault(l=>l.X>.75&&ScreenSignals.Clean(l.Text).Contains("most damage inflicted"));var suffered=lines.FirstOrDefault(l=>l.X>.75&&ScreenSignals.Clean(l.Text).Contains("most damage suffered"));if(inflicted==null||suffered==null||suffered.Y<=inflicted.Y)return null;
  double? used=null;var label=lines.FirstOrDefault(l=>l.X>.75&&l.Y<inflicted.Y&&ScreenSignals.Clean(l.Text)=="used");if(label!=null){var value=lines.FirstOrDefault(l=>l.X>.94&&Math.Abs(l.Y-label.Y)<.026);double n;if(value!=null&&double.TryParse(Text(value.Text)=="I"?"1":Text(value.Text),out n)&&n>=0&&n<=20)used=n;}
  var result=new VictoryRead{seconds=minutes*60+seconds,fear=used,inflicted=Rows(lines,inflicted.Y+.025,suffered.Y-.025),suffered=Rows(lines,suffered.Y+.025,.9)};return result.inflicted.Length>=2&&result.suffered.Length>=1?result:null;
 }
 static DamageRow[] Rows(ScreenLine[] lines,double top,double bottom){var rows=new List<DamageRow>();foreach(var label in lines.Where(l=>l.X>.76&&l.X<.91&&l.Y>top&&l.Y<bottom)){
  var value=lines.Where(l=>l.X>.92&&Math.Abs(l.Y-label.Y)<.017).OrderBy(l=>Math.Abs(l.Y-label.Y)).FirstOrDefault();double n;if(value==null||!double.TryParse(Regex.Replace(value.Text,@"[,\s]",""),NumberStyles.None,CultureInfo.InvariantCulture,out n)||n<=0)continue;
  string name=Text(label.Text);if(Regex.IsMatch(name,@"^[QΩΩO0] (Attack|Special)$"))name="Omega "+name.Substring(2);name=Regex.Replace(name,@"^[^A-Za-z]+","");rows.Add(new DamageRow{name=name,amount=n});
 }return rows.GroupBy(x=>x.name).Select(g=>g.First()).OrderByDescending(x=>x.amount).Take(5).ToArray();}
}
static class BuildSections {
 internal static readonly string[] Names={"Boons","Equipment","Arcana"};
 internal static string Category(RecapItem item){return item.category=="Arcana"?"Arcana":new[]{"Aspect","Keepsake","Weapon","Equipment"}.Contains(item.category)?"Equipment":"Boons";}
}
static class RecapDetails {
 internal static void Enrich(RunRecap r,SavedBuild b){if(b==null||b.profile!=r.profile||b.completedRuns+1!=r.number)return;foreach(var i in r.items){var t=(b.owned??new SavedTrait[0]).LastOrDefault(x=>x.id==i.id);if(t==null)continue;i.description=t.description;i.effects=t.effectDetails??new string[0];i.level=t.level;i.rank=t.rank;i.evidence="Last captured checkpoint";if(string.IsNullOrEmpty(i.rarity))i.rarity=t.rarity;}r.choices=b.choices??new SavedChoice[0];r.checkpointAt=b.savedAt;if(b.weapon!=null&&b.weapon.aspectName==r.aspect)r.aspectRank=b.weapon.aspectRank;}
 internal static RunRecap FromVictory(SavedBuild b,VictoryRead v){if(b==null||string.IsNullOrEmpty(b.profile)||!Regex.IsMatch(b.map??"",@"^[FGHINOPQ]_"))return null;var r=new RunRecap{profile=b.profile,number=b.completedRuns+1,result="Completed",cleared=true,resultEvidence="Victory screen; final save pending",route=Regex.IsMatch(b.map,@"^[NOPQ]_")?"Surface":"Underworld",endingRoom=b.map,weapon=b.weapon==null?"Weapon unrecorded":b.weapon.name,aspect=b.weapon==null?"Aspect unrecorded":b.weapon.aspectName,items=(b.owned??new SavedTrait[0]).Where(t=>t.name!=t.id&&!t.id.StartsWith("Dummy")).GroupBy(t=>t.id).Select(g=>g.Last()).Select(t=>new RecapItem{id=t.id,name=t.name,rarity=t.rarity,category=HistoryProjection.Category(t.id,BuildPlanner.Names)}).ToArray(),keepsakes=(b.owned??new SavedTrait[0]).Where(t=>t.category=="keepsake").Select(t=>t.name).ToArray(),seconds=v.seconds,victorySeconds=v.seconds,fear=v.fear,inflicted=v.inflicted,suffered=v.suffered,damageEvidence="Visible victory-screen leaders only",victoryAt=DateTime.UtcNow.ToString("o")};Enrich(r,b);return r;}
 internal static SynergyGroup[] Groups(RunRecap r){var groups=new List<SynergyGroup>();Action<string,string,string,string[],Func<RecapItem[],bool>> add=(title,why,condition,ids,valid)=>{var items=(r.items??new RecapItem[0]).Where(i=>ids.Contains(i.id)).ToArray();if(valid(items))groups.Add(new SynergyGroup{title=title,why=why,condition=condition,items=items});};
  string[] blast={"HephaestusWeaponBoon","HephaestusSpecialBoon","HephaestusSprintBoon","HephaestusCastBoon"};
  add("Blast engine","Your Hephaestus cores supply the blasts; Grand Caldera raises their power. Chain Reaction can repeat a freshly recharged blast.","Each core has its own recharge. Chain Reaction needs a blast within its timing window; it is not an unconditional damage doubling.",blast.Concat(new[]{"MassiveDamageBoon","DoubleMassiveAttackBoon"}).ToArray(),a=>a.Any(i=>blast.Contains(i.id))&&a.Any(i=>i.id=="MassiveDamageBoon"||i.id=="DoubleMassiveAttackBoon"));
  var engine=groups.LastOrDefault();if(engine!=null){engine.why="Your Hephaestus cores supply the blasts."+(engine.items.Any(i=>i.id=="MassiveDamageBoon")?" Grand Caldera raises their power and area.":"")+(engine.items.Any(i=>i.id=="DoubleMassiveAttackBoon")?" Chain Reaction can repeat a freshly recharged blast.":"");if(!engine.items.Any(i=>i.id=="DoubleMassiveAttackBoon"))engine.condition="Blast cores recharge separately; attack speed does not remove those cooldowns.";}
  string[] hitch={"HeraCastBoon","HeraWeaponBoon","HeraSpecialBoon","HeraSprintBoon"};
  add("Magick into Hitch damage","Incandescent Aura turns restored Magick into damage on Hitch-afflicted foes. Your recovery and Hitch application connect the two sides of that loop.","Hitch must be active and Magick must actually be restored. On-hit recovery requires landed hits; an already-full pool is not missing Magick to restore.",hitch.Concat(new[]{"ManaRestoreDamageBoon","HestiaManaBoon","HeraManaBoon","ZeusManaBoon","ApolloManaBoon","DemeterManaBoon","AphroditeManaBoon","PoseidonManaBoon","HephaestusManaBoon"}).ToArray(),a=>a.Any(i=>i.id=="ManaRestoreDamageBoon")&&a.Any(i=>hitch.Contains(i.id))&&a.Any(i=>i.category=="Magick"));
  add("Torch tempo","The recorded hammer upgrades shape how the Flames travel and how quickly the Omega Attack can be prepared.","Faster channeling and a lower cost help execution; they do not shorten an independent boon cooldown.",new[]{"TorchEnhancedAttackTrait","TorchDiscountExAttackTrait","TorchSpecialDurationAspect"},a=>a.Any(i=>i.id=="TorchEnhancedAttackTrait")&&a.Any(i=>i.id=="TorchDiscountExAttackTrait"));
  add("Cast setup","Your Cast binds targets while The Furies rewards damage dealt to foes inside it.","The target must remain inside the Cast. This is a positioning benefit, not a permanent damage bonus.",(r.items??new RecapItem[0]).Where(i=>i.category=="Cast").Select(i=>i.id).Concat(new[]{"InsideCastBuffMetaUpgrade"}).ToArray(),a=>a.Any(i=>i.category=="Cast")&&a.Any(i=>i.id=="InsideCastBuffMetaUpgrade"));
  add("Omega support","Magick recovery supports the costs of Omega moves, alongside Arcana that improve their execution or damage opportunities.","Read each component's trigger. Recovery uptime, Omega combo conditions and channel speed are separate effects.",(r.items??new RecapItem[0]).Where(i=>i.category=="Magick").Select(i=>i.id).Concat(new[]{"MagicCritMetaUpgrade","ChannelSlowMetaUpgrade","CastDamageMetaUpgrade"}).ToArray(),a=>a.Any(i=>i.category=="Magick")&&a.Any(i=>i.category=="Arcana"));
  add("Conditional damage boosts","These bonuses support your damage plan when their individual conditions are met.","High-Life and isolated-target bonuses are conditional. Their listed maxima are not proof of full uptime or separate measured damage.",new[]{"HighHealthOffenseBoon","AloneDamageBoon","ChaosWeaponBlessing","ChaosSpecialBlessing","LowManaDamageMetaupgrade"},a=>a.Length>=2);
  add("Recovery and safeguards","Between-room recovery and defensive tools help protect the damage engine you assembled.","Healing thresholds, limited uses and Guardian-only protection still apply; these effects do not all heal during combat.",new[]{"DoorHealToFullBoon","DoorHealMetaUpgrade","LastStandSlowTimeMetaUpgrade","BossPreDamageKeepsake","HealthRegenBoon","HealthRegen"},a=>a.Length>=2);
  return groups.ToArray();
 }
 internal static string Effect(RecapItem i){string text=string.Join(" ",new[]{i.description}.Concat(i.effects??new string[0]).Where(x=>!string.IsNullOrWhiteSpace(x)));text=Regex.Replace(text,@"\[unresolved [^\]]+\]","(value not retained)");return Regex.Replace(text,@"\[icon ([^\]]+)\]",m=>m.Groups[1].Value.StartsWith("Mana")?"Magick":m.Groups[1].Value=="EnemyHealth"?"Life":m.Groups[1].Value=="CurseFire"?"Fire":"");}
 internal static string Rarity(RecapItem i){return (string.IsNullOrEmpty(i.rarity)?"Rarity not retained":i.rarity)+(i.level>0?" · Lv. "+i.level:"")+(i.rank>0?" · rank "+i.rank:"");}
}
}
