using System;using System.Drawing;using System.IO;using System.Threading;using System.Windows.Forms;
namespace GameCoach {
sealed class RuntimeSettingsPanel:UserControl {
 readonly CheckBox managed;readonly TextBox engine,weights,projector,model;readonly NumericUpDown context;readonly Label result;readonly Button apply;readonly Func<bool> mayChange;
 internal RuntimeSettingsPanel(Func<bool> canChange){mayChange=canChange;AutoSize=true;Dock=DockStyle.Top;var cfg=LocalInference.Load();ManagedRuntime.Discover(cfg);var fields=Theme.Stack();
  managed=new CheckBox{Text="Start the local model with Game Coach",Checked=cfg.Managed,AutoSize=true};Theme.Hint(managed,"Enabled by default. Loads the model when the app opens, keeps it available while minimized, and releases an app-owned engine on exit. A healthy Hermes engine can be reused without taking ownership.");Theme.Row(fields,managed);
  Theme.Row(fields,Theme.Copy("These files stay on your PC. The model and its matching vision projector are both required. Pause coaching before changing startup settings."));
  engine=FileField(fields,"Local engine · llama-server.exe",cfg.RuntimePath,"llama-server.exe|llama-server.exe");weights=FileField(fields,"Model weights · GGUF",cfg.ModelPath,"GGUF model|*.gguf");projector=FileField(fields,"Vision projector · matching GGUF",cfg.ProjectorPath,"Vision projector|*.gguf");
  Theme.Row(fields,Theme.Copy("Local model ID"));model=new TextBox{Text=cfg.Model,AccessibleName="Managed local model ID"};Theme.Row(fields,model);
  Theme.Row(fields,Theme.Copy("Context tokens · advanced"));context=new NumericUpDown{Minimum=8192,Maximum=262144,Increment=8192,Value=Math.Max(8192,Math.Min(262144,cfg.ContextSize)),ThousandsSeparator=true,AccessibleName="Local context tokens"};Theme.Hint(context,"32,768 tokens is the app default. Larger contexts reserve more memory; they do not make responses faster.");Theme.Row(fields,context);
  apply=Theme.Action("Save & load model","check","Save startup settings and load the model locally. No game capture, microphone activation or Platform request.",null);result=Theme.Copy("External-server mode keeps connection details editable and leaves engine startup to you.");Theme.Row(fields,apply);Theme.Row(fields,result);
  apply.Click+=async(s,e)=>{if(!mayChange()){result.Text="Pause coaching and overlays before changing the local model.";return;}apply.Enabled=false;try{var value=LocalInference.Load();value.Managed=managed.Checked;value.RuntimePath=engine.Text.Trim();value.ModelPath=weights.Text.Trim();value.ProjectorPath=projector.Text.Trim();value.Model=model.Text.Trim();value.ContextSize=(int)context.Value;ManagedRuntime.Validate(value);ManagedRuntime.Invalidate();LocalInference.Save(value,"");result.Text="Preparing local model…";await ManagedRuntime.Ensure(CancellationToken.None);if(!IsDisposed)result.Text=ManagedRuntime.Status;}catch(Exception ex){if(!IsDisposed)result.Text=ex.Message;}finally{if(!IsDisposed)apply.Enabled=true;}};
  Controls.Add(Theme.Fold("Model startup","Choose automatic startup or an external server, and locate your model files.",fields));Theme.StyleInputs(this);
 }
 static TextBox FileField(TableLayoutPanel fields,string title,string value,string filter){Theme.Row(fields,Theme.Copy(title));var row=Theme.Stack(2);row.ColumnStyles[0].Width=100;row.ColumnStyles[1].SizeType=SizeType.AutoSize;var text=new TextBox{Text=value,Dock=DockStyle.Fill,AccessibleName=title,Margin=new Padding(0,6,8,0)};var browse=Theme.Action("Browse…","folder","Select "+title.ToLowerInvariant()+".",(s,e)=>{using(var dialog=new OpenFileDialog{Filter=filter,CheckFileExists=true,Title=title}){if(File.Exists(text.Text))dialog.FileName=text.Text;if(dialog.ShowDialog()==DialogResult.OK)text.Text=dialog.FileName;}});row.Controls.Add(text,0,0);row.Controls.Add(browse,1,0);Theme.Row(fields,row);return text;}
}
}
